-- NEW AXE NET v0.3
-- 002_members.sql
-- AXE WAR Supabase 프로젝트의 SQL Editor에서 실행합니다.
-- NEW AXE NET 전용 new_axe_net schema만 사용합니다.

create schema if not exists new_axe_net;

create table if not exists new_axe_net.members (
  id bigint generated by default as identity primary key,
  member_key text not null unique,
  discord_user_id text unique,
  discord_name text,
  nickname text not null,
  role text not null default 'user'
    check (role in ('admin', 'user')),
  status text not null default 'active'
    check (status in ('active', 'inactive', 'resigned')),
  joined_date date,
  last_login date,
  badge text,
  points integer not null default 0
    check (points >= 0),
  resigned_at date,
  memo text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists members_status_idx
  on new_axe_net.members (status);

create index if not exists members_sort_order_idx
  on new_axe_net.members (sort_order);

create or replace function new_axe_net.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists members_touch_updated_at
on new_axe_net.members;

create trigger members_touch_updated_at
before update on new_axe_net.members
for each row
execute function new_axe_net.touch_updated_at();

alter table new_axe_net.members enable row level security;

-- Base table is intentionally NOT exposed to anon/authenticated.
revoke all on table new_axe_net.members from anon, authenticated;

-- Browser-readable projection: excludes Discord numeric ID and memo.
create or replace view new_axe_net.members_app
with (security_invoker = false)
as
select
  member_key,
  discord_name,
  nickname,
  role,
  status,
  joined_date,
  last_login,
  badge,
  points,
  resigned_at,
  sort_order
from new_axe_net.members;

revoke all on new_axe_net.members_app from public;
grant select on new_axe_net.members_app to anon, authenticated;

-- Keep schema usable by the Data API.
grant usage on schema new_axe_net to anon, authenticated;

notify pgrst, 'reload schema';
