-- NEW AXE NET v0.7
-- 005_member_audit.sql
-- AXE WAR Supabase 프로젝트 > SQL Editor에서 전체 실행

create table if not exists new_axe_net.member_audit_log (
  id bigint generated by default as identity primary key,
  member_key text not null
    references new_axe_net.members(member_key)
    on delete cascade,
  changed_by uuid,
  changed_by_nickname text,
  changed_fields text[] not null default '{}'::text[],
  old_data jsonb not null,
  new_data jsonb not null,
  changed_at timestamptz not null default now()
);

create index if not exists member_audit_log_member_key_changed_at_idx
  on new_axe_net.member_audit_log (member_key, changed_at desc);

alter table new_axe_net.member_audit_log enable row level security;

revoke all on table new_axe_net.member_audit_log from anon, authenticated;
grant select on table new_axe_net.member_audit_log to authenticated;

drop policy if exists "member_audit_admin_read"
on new_axe_net.member_audit_log;

create policy "member_audit_admin_read"
on new_axe_net.member_audit_log
for select
to authenticated
using (new_axe_net.is_admin());

create or replace function new_axe_net.log_member_update()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_nickname text;
  fields text[] := array[]::text[];
  old_payload jsonb;
  new_payload jsonb;
begin
  if old.nickname is distinct from new.nickname then
    fields := array_append(fields, 'nickname');
  end if;

  if old.role is distinct from new.role then
    fields := array_append(fields, 'role');
  end if;

  if old.status is distinct from new.status then
    fields := array_append(fields, 'status');
  end if;

  if old.badge is distinct from new.badge then
    fields := array_append(fields, 'badge');
  end if;

  if old.points is distinct from new.points then
    fields := array_append(fields, 'points');
  end if;

  if old.resigned_at is distinct from new.resigned_at then
    fields := array_append(fields, 'resigned_at');
  end if;

  if cardinality(fields) = 0 then
    return new;
  end if;

  select member.nickname
    into actor_nickname
  from new_axe_net.admin_accounts account
  join new_axe_net.members member
    on member.member_key = account.member_key
  where account.user_id = auth.uid()
    and account.enabled = true
  limit 1;

  old_payload := jsonb_build_object(
    'nickname', old.nickname,
    'role', old.role,
    'status', old.status,
    'badge', old.badge,
    'points', old.points,
    'resigned_at', old.resigned_at
  );

  new_payload := jsonb_build_object(
    'nickname', new.nickname,
    'role', new.role,
    'status', new.status,
    'badge', new.badge,
    'points', new.points,
    'resigned_at', new.resigned_at
  );

  insert into new_axe_net.member_audit_log (
    member_key,
    changed_by,
    changed_by_nickname,
    changed_fields,
    old_data,
    new_data
  )
  values (
    new.member_key,
    auth.uid(),
    coalesce(actor_nickname, 'unknown'),
    fields,
    old_payload,
    new_payload
  );

  return new;
end;
$$;

drop trigger if exists members_audit_update
on new_axe_net.members;

create trigger members_audit_update
after update of nickname, role, status, badge, points, resigned_at
on new_axe_net.members
for each row
execute function new_axe_net.log_member_update();

notify pgrst, 'reload schema';
