-- NEW AXE NET v0.9
-- 007_fund_base.sql
-- AXE WAR Supabase 프로젝트 > SQL Editor에서 전체 실행
--
-- 설계 원칙
-- - fund_ledger = 실제 돈의 원장(source of truth)
-- - fund_fee_rules = 주간 공금 규칙
-- - fund_exemptions = 면제 이력
-- - fund_requests = 제출/검수 워크플로우 이력
-- - fund_status_snapshot = 레거시 계산 결과 보존용 스냅샷
-- - 기존 fund_members는 NEW에서 별도 복제하지 않음:
--   현재 CSV 18명이 NEW members의 active 18명과 정확히 일치하므로 members를 기준으로 사용

create table if not exists new_axe_net.fund_fee_rules (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  source_id text,
  start_year integer not null,
  start_month integer not null check (start_month between 1 and 12),
  start_week integer not null check (start_week between 1 and 5),
  weekly_fee integer not null check (weekly_fee >= 0),
  note text,
  enabled boolean not null default true,
  source_key text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists new_axe_net.fund_exemptions (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  member_key text not null
    references new_axe_net.members(member_key)
    on delete cascade,
  nickname text,
  year integer not null,
  month integer not null check (month between 1 and 12),
  week integer not null check (week between 1 and 5),
  exemption_type text not null default 'manual',
  reason text,
  enabled boolean not null default true,
  source_key text not null unique,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists fund_exemptions_one_enabled_period_idx
on new_axe_net.fund_exemptions (member_key, year, month, week)
where enabled = true;

create table if not exists new_axe_net.fund_status_snapshot (
  id bigint generated by default as identity primary key,
  legacy_id bigint not null unique,
  member_key text not null
    references new_axe_net.members(member_key)
    on delete cascade,
  nickname text,
  year integer not null,
  month integer not null check (month between 1 and 12),
  week integer not null check (week between 1 and 5),
  status text not null
    check (status in ('가입 전', '미납', '완료', '면제', '예정')),
  amount integer not null default 0,
  join_date date,
  note text,
  updated_at timestamptz not null default now(),
  unique (member_key, year, month, week)
);

create index if not exists fund_status_snapshot_period_idx
on new_axe_net.fund_status_snapshot (year, month, week);

create table if not exists new_axe_net.fund_requests (
  id bigint generated by default as identity primary key,
  legacy_id bigint not null unique,
  guild_id text,
  discord_user_id text,
  discord_name text,
  member_key text not null
    references new_axe_net.members(member_key),
  nickname text,
  year integer not null,
  month integer not null check (month between 1 and 12),
  week integer not null check (week between 1 and 5),
  amount integer not null check (amount >= 0),
  status text not null
    check (status in ('approved', 'rejected', 'deleted')),
  evidence_url text,
  memo text,
  reviewer_discord_name text,
  reviewed_at timestamptz,
  source_key text not null unique,
  payment_mode text
    check (payment_mode is null or payment_mode in ('공용계좌', '회사잔고')),
  public_amount integer not null default 0,
  company_amount integer not null default 0,
  client_request_id text,
  sheet_request_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists fund_requests_period_member_idx
on new_axe_net.fund_requests (year, month, week, member_key);

create table if not exists new_axe_net.fund_ledger (
  id bigint generated by default as identity primary key,
  legacy_id bigint not null unique,
  member_key text
    references new_axe_net.members(member_key),
  nickname text,
  year integer,
  month integer check (month is null or month between 1 and 12),
  week integer check (week is null or week between 1 and 5),
  entry_type text not null
    check (entry_type in ('payment', 'adjustment', 'refund')),
  amount integer not null,
  public_amount integer not null default 0,
  company_amount integer not null default 0,
  status text not null
    check (status in ('active', 'cancelled')),
  approved_by_name text,
  approved_at timestamptz,
  legacy_request_key text,
  source_key text not null unique,
  memo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  ledger_date timestamptz not null,
  ledger_type text not null,
  category text,
  direction text not null
    check (direction in ('수입', '지출', '조정')),
  account text not null
    check (account in ('공용계좌', '회사잔고')),
  evidence_url text,
  evidence_file_id text,
  operation_key text
);

create index if not exists fund_ledger_active_date_idx
on new_axe_net.fund_ledger (status, ledger_date desc);

create index if not exists fund_ledger_period_member_idx
on new_axe_net.fund_ledger (year, month, week, member_key);

-- Base tables는 브라우저에서 직접 읽지 않는다.
alter table new_axe_net.fund_fee_rules enable row level security;
alter table new_axe_net.fund_exemptions enable row level security;
alter table new_axe_net.fund_status_snapshot enable row level security;
alter table new_axe_net.fund_requests enable row level security;
alter table new_axe_net.fund_ledger enable row level security;

revoke all on table new_axe_net.fund_fee_rules from anon, authenticated;
revoke all on table new_axe_net.fund_exemptions from anon, authenticated;
revoke all on table new_axe_net.fund_status_snapshot from anon, authenticated;
revoke all on table new_axe_net.fund_requests from anon, authenticated;
revoke all on table new_axe_net.fund_ledger from anon, authenticated;

-- 관리자는 원본 데이터 조회 가능.
grant select on table new_axe_net.fund_fee_rules to authenticated;
grant select on table new_axe_net.fund_exemptions to authenticated;
grant select on table new_axe_net.fund_status_snapshot to authenticated;
grant select on table new_axe_net.fund_requests to authenticated;
grant select on table new_axe_net.fund_ledger to authenticated;

drop policy if exists "fund_fee_rules_admin_read" on new_axe_net.fund_fee_rules;
create policy "fund_fee_rules_admin_read"
on new_axe_net.fund_fee_rules
for select to authenticated
using (new_axe_net.is_admin());

drop policy if exists "fund_exemptions_admin_read" on new_axe_net.fund_exemptions;
create policy "fund_exemptions_admin_read"
on new_axe_net.fund_exemptions
for select to authenticated
using (new_axe_net.is_admin());

drop policy if exists "fund_status_snapshot_admin_read" on new_axe_net.fund_status_snapshot;
create policy "fund_status_snapshot_admin_read"
on new_axe_net.fund_status_snapshot
for select to authenticated
using (new_axe_net.is_admin());

drop policy if exists "fund_requests_admin_read" on new_axe_net.fund_requests;
create policy "fund_requests_admin_read"
on new_axe_net.fund_requests
for select to authenticated
using (new_axe_net.is_admin());

drop policy if exists "fund_ledger_admin_read" on new_axe_net.fund_ledger;
create policy "fund_ledger_admin_read"
on new_axe_net.fund_ledger
for select to authenticated
using (new_axe_net.is_admin());

-- 기간 목록: 공개 가능한 집계만 반환
create or replace function new_axe_net.get_fund_periods()
returns table (
  year integer,
  month integer,
  week integer,
  member_count bigint,
  completed_count bigint,
  unpaid_count bigint,
  exempt_count bigint,
  scheduled_count bigint,
  before_join_count bigint
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    s.year,
    s.month,
    s.week,
    count(*) as member_count,
    count(*) filter (where s.status = '완료') as completed_count,
    count(*) filter (where s.status = '미납') as unpaid_count,
    count(*) filter (where s.status = '면제') as exempt_count,
    count(*) filter (where s.status = '예정') as scheduled_count,
    count(*) filter (where s.status = '가입 전') as before_join_count
  from new_axe_net.fund_status_snapshot s
  group by s.year, s.month, s.week
  order by s.year desc, s.month desc, s.week desc;
$$;

-- 선택 기간 요약 + 현재 전체 잔액
create or replace function new_axe_net.get_fund_summary(
  p_year integer default null,
  p_month integer default null,
  p_week integer default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_year integer;
  v_month integer;
  v_week integer;
  v_fee integer := 0;

  v_member_count bigint := 0;
  v_completed bigint := 0;
  v_unpaid bigint := 0;
  v_exempt bigint := 0;
  v_scheduled bigint := 0;
  v_before_join bigint := 0;

  v_expected bigint := 0;
  v_paid bigint := 0;
  v_unpaid_amount bigint := 0;
  v_exempt_amount bigint := 0;

  v_public_balance bigint := 0;
  v_company_balance bigint := 0;
begin
  if p_year is null or p_month is null or p_week is null then
    select p.year, p.month, p.week
      into v_year, v_month, v_week
    from (
      select
        s.year,
        s.month,
        s.week
      from new_axe_net.fund_status_snapshot s
      group by s.year, s.month, s.week
      having bool_or(s.status <> '예정')
      order by s.year desc, s.month desc, s.week desc
      limit 1
    ) p;
  else
    v_year := p_year;
    v_month := p_month;
    v_week := p_week;
  end if;

  if v_year is null then
    return jsonb_build_object(
      'period', null,
      'balance', jsonb_build_object('total', 0, 'public', 0, 'company', 0),
      'fee', 0,
      'counts', jsonb_build_object(),
      'amounts', jsonb_build_object()
    );
  end if;

  select r.weekly_fee
    into v_fee
  from new_axe_net.fund_fee_rules r
  where r.enabled = true
    and (r.start_year, r.start_month, r.start_week)
      <= (v_year, v_month, v_week)
  order by r.start_year desc, r.start_month desc, r.start_week desc, r.id desc
  limit 1;

  select
    count(*),
    count(*) filter (where s.status = '완료'),
    count(*) filter (where s.status = '미납'),
    count(*) filter (where s.status = '면제'),
    count(*) filter (where s.status = '예정'),
    count(*) filter (where s.status = '가입 전'),
    coalesce(sum(s.amount) filter (where s.status in ('완료', '미납')), 0),
    coalesce(sum(s.amount) filter (where s.status = '완료'), 0),
    coalesce(sum(s.amount) filter (where s.status = '미납'), 0),
    coalesce(sum(s.amount) filter (where s.status = '면제'), 0)
  into
    v_member_count,
    v_completed,
    v_unpaid,
    v_exempt,
    v_scheduled,
    v_before_join,
    v_expected,
    v_paid,
    v_unpaid_amount,
    v_exempt_amount
  from new_axe_net.fund_status_snapshot s
  where s.year = v_year
    and s.month = v_month
    and s.week = v_week;

  select
    coalesce(sum(
      case l.direction
        when '수입' then l.public_amount
        when '지출' then -l.public_amount
        when '조정' then l.public_amount
        else 0
      end
    ), 0),
    coalesce(sum(
      case l.direction
        when '수입' then l.company_amount
        when '지출' then -l.company_amount
        when '조정' then l.company_amount
        else 0
      end
    ), 0)
  into v_public_balance, v_company_balance
  from new_axe_net.fund_ledger l
  where l.status = 'active';

  return jsonb_build_object(
    'period', jsonb_build_object(
      'year', v_year,
      'month', v_month,
      'week', v_week
    ),
    'balance', jsonb_build_object(
      'total', v_public_balance + v_company_balance,
      'public', v_public_balance,
      'company', v_company_balance
    ),
    'fee', coalesce(v_fee, 0),
    'counts', jsonb_build_object(
      'members', v_member_count,
      'completed', v_completed,
      'unpaid', v_unpaid,
      'exempt', v_exempt,
      'scheduled', v_scheduled,
      'before_join', v_before_join
    ),
    'amounts', jsonb_build_object(
      'expected', v_expected,
      'paid', v_paid,
      'unpaid', v_unpaid_amount,
      'exempt', v_exempt_amount
    )
  );
end;
$$;

-- 선택 기간 멤버별 상태
create or replace function new_axe_net.get_fund_period_status(
  p_year integer,
  p_month integer,
  p_week integer
)
returns table (
  sort_order integer,
  nickname text,
  status text,
  amount integer,
  join_date date
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    m.sort_order,
    s.nickname,
    s.status,
    s.amount,
    s.join_date
  from new_axe_net.fund_status_snapshot s
  join new_axe_net.members m
    on m.member_key = s.member_key
  where s.year = p_year
    and s.month = p_month
    and s.week = p_week
  order by m.sort_order;
$$;

-- 공개 화면용 최근 원장: 메모/증빙 URL/내부키는 제외
create or replace function new_axe_net.get_fund_recent_ledger(
  p_limit integer default 12
)
returns table (
  ledger_date timestamptz,
  nickname text,
  ledger_type text,
  category text,
  direction text,
  account text,
  amount integer
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    l.ledger_date,
    l.nickname,
    l.ledger_type,
    l.category,
    l.direction,
    l.account,
    l.amount
  from new_axe_net.fund_ledger l
  where l.status = 'active'
  order by l.ledger_date desc, l.id desc
  limit least(greatest(coalesce(p_limit, 12), 1), 50);
$$;

revoke all on function new_axe_net.get_fund_periods() from public;
revoke all on function new_axe_net.get_fund_summary(integer, integer, integer) from public;
revoke all on function new_axe_net.get_fund_period_status(integer, integer, integer) from public;
revoke all on function new_axe_net.get_fund_recent_ledger(integer) from public;

grant execute on function new_axe_net.get_fund_periods()
to anon, authenticated;

grant execute on function new_axe_net.get_fund_summary(integer, integer, integer)
to anon, authenticated;

grant execute on function new_axe_net.get_fund_period_status(integer, integer, integer)
to anon, authenticated;

grant execute on function new_axe_net.get_fund_recent_ledger(integer)
to anon, authenticated;

grant usage on schema new_axe_net to anon, authenticated;

notify pgrst, 'reload schema';
