-- NEW AXE NET v1.1
-- 009_fund_admin.sql
-- AXE WAR Supabase 프로젝트 > SQL Editor에서 전체 실행
--
-- 추가 기능
-- 1) 공금 면제 등록/해제
-- 2) 주간 공금 규칙 추가/활성화/비활성화
-- 3) 관리자 공금 설정 변경 감사 로그
--
-- 브라우저에 fund_* 테이블의 직접 쓰기 권한은 열지 않습니다.
-- 모든 쓰기는 is_admin()을 다시 확인하는 SECURITY DEFINER RPC로 처리합니다.

-- --------------------------------------------------
-- updated_at 자동 갱신
-- --------------------------------------------------

drop trigger if exists fund_fee_rules_touch_updated_at
on new_axe_net.fund_fee_rules;

create trigger fund_fee_rules_touch_updated_at
before update on new_axe_net.fund_fee_rules
for each row
execute function new_axe_net.touch_updated_at();

drop trigger if exists fund_exemptions_touch_updated_at
on new_axe_net.fund_exemptions;

create trigger fund_exemptions_touch_updated_at
before update on new_axe_net.fund_exemptions
for each row
execute function new_axe_net.touch_updated_at();

-- 동일 적용시점에 활성화된 회비 규칙은 하나만 허용
create unique index if not exists fund_fee_rules_one_enabled_period_idx
on new_axe_net.fund_fee_rules (
  start_year,
  start_month,
  start_week
)
where enabled = true;

-- --------------------------------------------------
-- 관리자 공금 변경 감사 로그
-- --------------------------------------------------

create table if not exists new_axe_net.fund_admin_audit_log (
  id bigint generated by default as identity primary key,
  action text not null,
  target_type text not null,
  target_key text,
  actor_user_id uuid,
  actor_nickname text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists fund_admin_audit_log_created_at_idx
on new_axe_net.fund_admin_audit_log (created_at desc);

alter table new_axe_net.fund_admin_audit_log enable row level security;

revoke all on table new_axe_net.fund_admin_audit_log
from anon, authenticated;

grant select on table new_axe_net.fund_admin_audit_log
to authenticated;

drop policy if exists "fund_admin_audit_read"
on new_axe_net.fund_admin_audit_log;

create policy "fund_admin_audit_read"
on new_axe_net.fund_admin_audit_log
for select
to authenticated
using (new_axe_net.is_admin());

create or replace function new_axe_net.fund_actor_nickname()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select m.nickname
  from new_axe_net.admin_accounts a
  join new_axe_net.members m
    on m.member_key = a.member_key
  where a.user_id = auth.uid()
    and a.enabled = true
  limit 1;
$$;

revoke all on function new_axe_net.fund_actor_nickname()
from public, anon;

grant execute on function new_axe_net.fund_actor_nickname()
to authenticated;

-- --------------------------------------------------
-- 면제 등록
-- --------------------------------------------------

create or replace function new_axe_net.create_fund_exemption(
  p_member_key text,
  p_year integer,
  p_month integer,
  p_week integer,
  p_reason text default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id bigint;
  v_nickname text;
  v_actor text;
  v_source_key text;
begin
  if not new_axe_net.is_admin() then
    raise exception '관리자 권한이 필요합니다.'
      using errcode = '42501';
  end if;

  if new_axe_net.fund_period_end(p_year, p_month, p_week) is null then
    raise exception '존재하지 않는 공금 주차입니다.'
      using errcode = '22023';
  end if;

  select m.nickname
    into v_nickname
  from new_axe_net.members m
  where m.member_key = p_member_key
    and m.status = 'active'
  limit 1;

  if v_nickname is null then
    raise exception '활동 중인 멤버를 찾을 수 없습니다.'
      using errcode = '22023';
  end if;

  if exists (
    select 1
    from new_axe_net.fund_exemptions e
    where e.member_key = p_member_key
      and e.year = p_year
      and e.month = p_month
      and e.week = p_week
      and e.enabled = true
  ) then
    raise exception '이미 해당 주차에 면제 등록된 멤버입니다.'
      using errcode = '23505';
  end if;

  v_actor := coalesce(
    new_axe_net.fund_actor_nickname(),
    'unknown'
  );

  v_source_key :=
    'new_fund_exemption:' ||
    floor(extract(epoch from clock_timestamp()) * 1000)::bigint::text ||
    ':' ||
    substr(
      md5(
        random()::text ||
        p_member_key ||
        clock_timestamp()::text
      ),
      1,
      10
    );

  insert into new_axe_net.fund_exemptions (
    member_key,
    nickname,
    year,
    month,
    week,
    exemption_type,
    reason,
    enabled,
    source_key,
    created_by
  )
  values (
    p_member_key,
    v_nickname,
    p_year,
    p_month,
    p_week,
    'manual',
    nullif(btrim(p_reason), ''),
    true,
    v_source_key,
    v_actor
  )
  returning id into v_id;

  insert into new_axe_net.fund_admin_audit_log (
    action,
    target_type,
    target_key,
    actor_user_id,
    actor_nickname,
    payload
  )
  values (
    'create_exemption',
    'fund_exemption',
    v_id::text,
    auth.uid(),
    v_actor,
    jsonb_build_object(
      'member_key', p_member_key,
      'nickname', v_nickname,
      'year', p_year,
      'month', p_month,
      'week', p_week,
      'reason', nullif(btrim(p_reason), '')
    )
  );

  return v_id;
end;
$$;

-- --------------------------------------------------
-- 면제 해제
-- 과거 기록은 삭제하지 않고 enabled=false로 보존
-- --------------------------------------------------

create or replace function new_axe_net.disable_fund_exemption(
  p_exemption_id bigint
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row new_axe_net.fund_exemptions%rowtype;
  v_actor text;
begin
  if not new_axe_net.is_admin() then
    raise exception '관리자 권한이 필요합니다.'
      using errcode = '42501';
  end if;

  select *
    into v_row
  from new_axe_net.fund_exemptions
  where id = p_exemption_id
    and enabled = true
  for update;

  if not found then
    raise exception '활성 면제 기록을 찾을 수 없습니다.'
      using errcode = '22023';
  end if;

  update new_axe_net.fund_exemptions
  set enabled = false
  where id = p_exemption_id;

  v_actor := coalesce(
    new_axe_net.fund_actor_nickname(),
    'unknown'
  );

  insert into new_axe_net.fund_admin_audit_log (
    action,
    target_type,
    target_key,
    actor_user_id,
    actor_nickname,
    payload
  )
  values (
    'disable_exemption',
    'fund_exemption',
    p_exemption_id::text,
    auth.uid(),
    v_actor,
    jsonb_build_object(
      'member_key', v_row.member_key,
      'nickname', v_row.nickname,
      'year', v_row.year,
      'month', v_row.month,
      'week', v_row.week,
      'reason', v_row.reason
    )
  );
end;
$$;

-- --------------------------------------------------
-- 주간 공금 규칙 추가
-- 기존 규칙을 수정하지 않고 새 적용 시점을 추가
-- --------------------------------------------------

create or replace function new_axe_net.create_fund_fee_rule(
  p_start_year integer,
  p_start_month integer,
  p_start_week integer,
  p_weekly_fee integer,
  p_note text default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id bigint;
  v_actor text;
  v_source_key text;
begin
  if not new_axe_net.is_admin() then
    raise exception '관리자 권한이 필요합니다.'
      using errcode = '42501';
  end if;

  if new_axe_net.fund_period_end(
    p_start_year,
    p_start_month,
    p_start_week
  ) is null then
    raise exception '존재하지 않는 공금 주차입니다.'
      using errcode = '22023';
  end if;

  if p_weekly_fee is null or p_weekly_fee < 0 then
    raise exception '주간 공금은 0원 이상의 정수여야 합니다.'
      using errcode = '22023';
  end if;

  if exists (
    select 1
    from new_axe_net.fund_fee_rules r
    where r.start_year = p_start_year
      and r.start_month = p_start_month
      and r.start_week = p_start_week
      and r.enabled = true
  ) then
    raise exception '해당 적용 시점에 이미 활성 회비 규칙이 있습니다.'
      using errcode = '23505';
  end if;

  v_actor := coalesce(
    new_axe_net.fund_actor_nickname(),
    'unknown'
  );

  v_source_key :=
    'new_fund_fee:' ||
    floor(extract(epoch from clock_timestamp()) * 1000)::bigint::text ||
    ':' ||
    substr(
      md5(
        random()::text ||
        p_start_year::text ||
        p_start_month::text ||
        p_start_week::text ||
        clock_timestamp()::text
      ),
      1,
      10
    );

  insert into new_axe_net.fund_fee_rules (
    source_id,
    start_year,
    start_month,
    start_week,
    weekly_fee,
    note,
    enabled,
    source_key
  )
  values (
    'new_axe_net',
    p_start_year,
    p_start_month,
    p_start_week,
    p_weekly_fee,
    nullif(btrim(p_note), ''),
    true,
    v_source_key
  )
  returning id into v_id;

  insert into new_axe_net.fund_admin_audit_log (
    action,
    target_type,
    target_key,
    actor_user_id,
    actor_nickname,
    payload
  )
  values (
    'create_fee_rule',
    'fund_fee_rule',
    v_id::text,
    auth.uid(),
    v_actor,
    jsonb_build_object(
      'start_year', p_start_year,
      'start_month', p_start_month,
      'start_week', p_start_week,
      'weekly_fee', p_weekly_fee,
      'note', nullif(btrim(p_note), '')
    )
  );

  return v_id;
end;
$$;

-- --------------------------------------------------
-- 회비 규칙 활성/비활성
-- base_weekly_fee는 안전망이므로 비활성화 금지
-- --------------------------------------------------

create or replace function new_axe_net.set_fund_fee_rule_enabled(
  p_rule_id bigint,
  p_enabled boolean
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row new_axe_net.fund_fee_rules%rowtype;
  v_actor text;
begin
  if not new_axe_net.is_admin() then
    raise exception '관리자 권한이 필요합니다.'
      using errcode = '42501';
  end if;

  select *
    into v_row
  from new_axe_net.fund_fee_rules
  where id = p_rule_id
  for update;

  if not found then
    raise exception '회비 규칙을 찾을 수 없습니다.'
      using errcode = '22023';
  end if;

  if v_row.source_key = 'base_weekly_fee'
     and p_enabled = false then
    raise exception '기본 fallback 회비 규칙은 비활성화할 수 없습니다.'
      using errcode = '22023';
  end if;

  if p_enabled = true and exists (
    select 1
    from new_axe_net.fund_fee_rules r
    where r.id <> p_rule_id
      and r.start_year = v_row.start_year
      and r.start_month = v_row.start_month
      and r.start_week = v_row.start_week
      and r.enabled = true
  ) then
    raise exception '동일 적용 시점에 다른 활성 회비 규칙이 있습니다.'
      using errcode = '23505';
  end if;

  update new_axe_net.fund_fee_rules
  set enabled = p_enabled
  where id = p_rule_id;

  v_actor := coalesce(
    new_axe_net.fund_actor_nickname(),
    'unknown'
  );

  insert into new_axe_net.fund_admin_audit_log (
    action,
    target_type,
    target_key,
    actor_user_id,
    actor_nickname,
    payload
  )
  values (
    case
      when p_enabled then 'enable_fee_rule'
      else 'disable_fee_rule'
    end,
    'fund_fee_rule',
    p_rule_id::text,
    auth.uid(),
    v_actor,
    jsonb_build_object(
      'start_year', v_row.start_year,
      'start_month', v_row.start_month,
      'start_week', v_row.start_week,
      'weekly_fee', v_row.weekly_fee,
      'enabled', p_enabled
    )
  );
end;
$$;

-- --------------------------------------------------
-- 권한
-- --------------------------------------------------

revoke all on function new_axe_net.create_fund_exemption(
  text,
  integer,
  integer,
  integer,
  text
) from public, anon;

revoke all on function new_axe_net.disable_fund_exemption(bigint)
from public, anon;

revoke all on function new_axe_net.create_fund_fee_rule(
  integer,
  integer,
  integer,
  integer,
  text
) from public, anon;

revoke all on function new_axe_net.set_fund_fee_rule_enabled(
  bigint,
  boolean
) from public, anon;

grant execute on function new_axe_net.create_fund_exemption(
  text,
  integer,
  integer,
  integer,
  text
) to authenticated;

grant execute on function new_axe_net.disable_fund_exemption(bigint)
to authenticated;

grant execute on function new_axe_net.create_fund_fee_rule(
  integer,
  integer,
  integer,
  integer,
  text
) to authenticated;

grant execute on function new_axe_net.set_fund_fee_rule_enabled(
  bigint,
  boolean
) to authenticated;

notify pgrst, 'reload schema';
