-- NEW AXE NET v1.11.0
-- 016_member_web_sessions.sql
-- AXE WAR Supabase 프로젝트 > SQL Editor에서 전체 실행
--
-- 목적
-- 1) 기존 AXE NET 닉네임/비밀번호 로그인을 NEW AXE NET 웹 세션으로 안전하게 연결
-- 2) 일반 멤버가 Discord 숫자 ID를 직접 입력하지 않아도 본인 공금정보를 조회/제출
-- 3) 세션 원문 토큰은 HttpOnly 쿠키로 전달하고 DB에는 SHA-256 해시만 저장
-- 4) 브라우저에서 이 테이블을 직접 읽거나 수정하지 못하도록 차단
--
-- 중요
-- - 실제 로그인 검증은 Vercel 서버 API가 기존 AXE NET Apps Script에 요청합니다.
-- - 이 테이블은 SUPABASE_SERVICE_ROLE_KEY를 가진 서버에서만 사용합니다.
-- - service role 키를 VITE_ 환경변수로 만들거나 GitHub에 커밋하면 안 됩니다.

create schema if not exists new_axe_net;

create table if not exists new_axe_net.member_web_sessions (
  id bigint generated by default as identity primary key,
  member_key text not null
    references new_axe_net.members(member_key)
    on update cascade
    on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint member_web_sessions_token_hash_check
    check (length(token_hash) = 64)
);

create index if not exists member_web_sessions_member_idx
on new_axe_net.member_web_sessions (member_key, expires_at desc);

create index if not exists member_web_sessions_expiry_idx
on new_axe_net.member_web_sessions (expires_at);

alter table new_axe_net.member_web_sessions enable row level security;

-- 일반 브라우저 역할은 세션 원장에 접근할 수 없습니다.
revoke all on table new_axe_net.member_web_sessions from anon, authenticated;
revoke all on sequence new_axe_net.member_web_sessions_id_seq from anon, authenticated;

-- Vercel 서버 전용 권한.
grant usage on schema new_axe_net to service_role;
grant select, insert, update, delete on table new_axe_net.member_web_sessions to service_role;
grant usage, select on sequence new_axe_net.member_web_sessions_id_seq to service_role;
grant select, update on table new_axe_net.members to service_role;

-- 서버가 기존의 검증된 공금 RPC를 대리 호출합니다.
grant execute on function new_axe_net.get_my_fund_profile(text, text) to service_role;
grant execute on function new_axe_net.submit_fund_request(
  text, text, integer, integer, integer, integer, text, text, text
) to service_role;

-- 만료 세션 정리용. service_role에서만 호출합니다.
create or replace function new_axe_net.cleanup_expired_member_web_sessions()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count integer;
begin
  delete from new_axe_net.member_web_sessions
  where expires_at <= now();

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

revoke all on function new_axe_net.cleanup_expired_member_web_sessions() from public;
grant execute on function new_axe_net.cleanup_expired_member_web_sessions() to service_role;
