-- NEW AXE NET v1.25.0
-- 021_notice_operations.sql
-- 공지사항 + 운영기준 Supabase-first 전환
--
-- 기존 AXE NET 기준
-- - 공지사항: 일반공지 / 패치노트, 중요 표시, 제목/내용/작성일/작성자
-- - 운영기준: id / category / title / content / order 순서 기반 목록
--
-- 전제: 001 ~ 020 마이그레이션 적용 완료

create schema if not exists new_axe_net;
grant usage on schema new_axe_net to anon, authenticated;

-- =========================================================
-- 1) 공지사항
-- =========================================================

create table if not exists new_axe_net.notices (
  id bigint generated by default as identity primary key,
  legacy_id text unique,
  notice_type text not null default '일반공지'
    check (notice_type in ('일반공지', '패치노트')),
  title text not null,
  content text not null,
  important boolean not null default false,
  writer text,
  published_at timestamptz not null default now(),
  status text not null default 'published'
    check (status in ('published', 'deleted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists notices_status_type_published_idx
  on new_axe_net.notices (status, notice_type, published_at desc);

create index if not exists notices_important_published_idx
  on new_axe_net.notices (important desc, published_at desc);

drop trigger if exists notices_touch_updated_at
on new_axe_net.notices;

create trigger notices_touch_updated_at
before update on new_axe_net.notices
for each row
execute function new_axe_net.touch_updated_at();

alter table new_axe_net.notices enable row level security;
revoke all on table new_axe_net.notices from anon, authenticated;

-- 브라우저에는 삭제되지 않은 공지만 노출합니다.
create or replace view new_axe_net.notices_app
with (security_invoker = false)
as
select
  id,
  legacy_id,
  notice_type,
  title,
  content,
  important,
  writer,
  published_at,
  updated_at
from new_axe_net.notices
where status = 'published';

revoke all on new_axe_net.notices_app from public;
grant select on new_axe_net.notices_app to anon, authenticated;

-- =========================================================
-- 2) 운영기준
-- =========================================================

create table if not exists new_axe_net.operation_rules (
  id bigint generated by default as identity primary key,
  legacy_id text unique,
  category text not null default '기본',
  title text not null,
  content text not null,
  sort_order integer not null default 0
    check (sort_order >= 0),
  active boolean not null default true,
  writer text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists operation_rules_active_order_idx
  on new_axe_net.operation_rules (active, sort_order, id);

create index if not exists operation_rules_category_order_idx
  on new_axe_net.operation_rules (category, sort_order, id);

drop trigger if exists operation_rules_touch_updated_at
on new_axe_net.operation_rules;

create trigger operation_rules_touch_updated_at
before update on new_axe_net.operation_rules
for each row
execute function new_axe_net.touch_updated_at();

alter table new_axe_net.operation_rules enable row level security;
revoke all on table new_axe_net.operation_rules from anon, authenticated;

create or replace view new_axe_net.operation_rules_app
with (security_invoker = false)
as
select
  id,
  legacy_id,
  category,
  title,
  content,
  sort_order,
  writer,
  updated_at
from new_axe_net.operation_rules
where active = true;

revoke all on new_axe_net.operation_rules_app from public;
grant select on new_axe_net.operation_rules_app to anon, authenticated;

-- =========================================================
-- 3) 관리자 공지 저장 / 삭제
-- =========================================================

create or replace function new_axe_net.save_notice(
  p_id bigint,
  p_notice_type text,
  p_title text,
  p_content text,
  p_important boolean
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id bigint;
  v_type text;
  v_title text;
  v_content text;
  v_writer text;
begin
  if not new_axe_net.is_admin() then
    raise exception '관리자 권한이 필요합니다.'
      using errcode = '42501';
  end if;

  v_type := case
    when btrim(coalesce(p_notice_type, '')) = '패치노트' then '패치노트'
    else '일반공지'
  end;
  v_title := nullif(btrim(coalesce(p_title, '')), '');
  v_content := nullif(btrim(coalesce(p_content, '')), '');

  if v_title is null then
    raise exception '공지 제목을 입력하세요.'
      using errcode = '22023';
  end if;

  if v_content is null then
    raise exception '공지 내용을 입력하세요.'
      using errcode = '22023';
  end if;

  select member.nickname
    into v_writer
  from new_axe_net.admin_accounts account
  join new_axe_net.members member
    on member.member_key = account.member_key
  where account.user_id = auth.uid()
    and account.enabled = true
  limit 1;

  if p_id is null then
    insert into new_axe_net.notices (
      notice_type,
      title,
      content,
      important,
      writer,
      published_at,
      status
    )
    values (
      v_type,
      v_title,
      v_content,
      coalesce(p_important, false),
      coalesce(v_writer, 'ADMIN'),
      now(),
      'published'
    )
    returning id into v_id;
  else
    update new_axe_net.notices
       set notice_type = v_type,
           title = v_title,
           content = v_content,
           important = coalesce(p_important, false),
           status = 'published'
     where id = p_id
     returning id into v_id;

    if v_id is null then
      raise exception '수정할 공지를 찾을 수 없습니다.'
        using errcode = 'P0002';
    end if;
  end if;

  return v_id;
end;
$$;

create or replace function new_axe_net.delete_notice(
  p_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count integer;
begin
  if not new_axe_net.is_admin() then
    raise exception '관리자 권한이 필요합니다.'
      using errcode = '42501';
  end if;

  update new_axe_net.notices
     set status = 'deleted'
   where id = p_id
     and status <> 'deleted';

  get diagnostics v_count = row_count;
  return v_count > 0;
end;
$$;

-- =========================================================
-- 4) 관리자 운영기준 저장 / 내리기
-- =========================================================

create or replace function new_axe_net.save_operation_rule(
  p_id bigint,
  p_category text,
  p_title text,
  p_content text,
  p_sort_order integer
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id bigint;
  v_category text;
  v_title text;
  v_content text;
  v_order integer;
  v_writer text;
begin
  if not new_axe_net.is_admin() then
    raise exception '관리자 권한이 필요합니다.'
      using errcode = '42501';
  end if;

  v_category := nullif(btrim(coalesce(p_category, '')), '');
  v_title := nullif(btrim(coalesce(p_title, '')), '');
  v_content := nullif(btrim(coalesce(p_content, '')), '');
  v_order := coalesce(p_sort_order, 0);

  if v_category is null then
    raise exception '운영기준 분류를 입력하세요.'
      using errcode = '22023';
  end if;

  if v_title is null then
    raise exception '운영기준 제목을 입력하세요.'
      using errcode = '22023';
  end if;

  if v_content is null then
    raise exception '운영기준 내용을 입력하세요.'
      using errcode = '22023';
  end if;

  if v_order < 0 then
    raise exception '정렬 순서는 0 이상이어야 합니다.'
      using errcode = '22023';
  end if;

  select member.nickname
    into v_writer
  from new_axe_net.admin_accounts account
  join new_axe_net.members member
    on member.member_key = account.member_key
  where account.user_id = auth.uid()
    and account.enabled = true
  limit 1;

  if p_id is null then
    insert into new_axe_net.operation_rules (
      category,
      title,
      content,
      sort_order,
      active,
      writer
    )
    values (
      v_category,
      v_title,
      v_content,
      v_order,
      true,
      coalesce(v_writer, 'ADMIN')
    )
    returning id into v_id;
  else
    update new_axe_net.operation_rules
       set category = v_category,
           title = v_title,
           content = v_content,
           sort_order = v_order,
           active = true
     where id = p_id
     returning id into v_id;

    if v_id is null then
      raise exception '수정할 운영기준을 찾을 수 없습니다.'
        using errcode = 'P0002';
    end if;
  end if;

  return v_id;
end;
$$;

create or replace function new_axe_net.delete_operation_rule(
  p_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count integer;
begin
  if not new_axe_net.is_admin() then
    raise exception '관리자 권한이 필요합니다.'
      using errcode = '42501';
  end if;

  update new_axe_net.operation_rules
     set active = false
   where id = p_id
     and active = true;

  get diagnostics v_count = row_count;
  return v_count > 0;
end;
$$;

-- =========================================================
-- 5) Data API 실행 권한
-- =========================================================

revoke all on function new_axe_net.save_notice(bigint, text, text, text, boolean) from public, anon;
grant execute on function new_axe_net.save_notice(bigint, text, text, text, boolean) to authenticated;

revoke all on function new_axe_net.delete_notice(bigint) from public, anon;
grant execute on function new_axe_net.delete_notice(bigint) to authenticated;

revoke all on function new_axe_net.save_operation_rule(bigint, text, text, text, integer) from public, anon;
grant execute on function new_axe_net.save_operation_rule(bigint, text, text, text, integer) to authenticated;

revoke all on function new_axe_net.delete_operation_rule(bigint) from public, anon;
grant execute on function new_axe_net.delete_operation_rule(bigint) to authenticated;

notify pgrst, 'reload schema';
