-- NEW AXE NET v1.26.0
-- 023_info_module.sql
-- 정보 모듈: 제작 / 퀘스트 / 가공·재련 / 개조서 / 스킬랭크
--
-- 전제: 001 ~ 022 적용 완료

create schema if not exists new_axe_net;
grant usage on schema new_axe_net to anon, authenticated, service_role;

-- =========================================================
-- 1) 기준 정보 테이블
-- =========================================================

create table if not exists new_axe_net.info_crafts (
  id text primary key,
  category text not null,
  item_name text not null,
  success_rate integer,
  craft_rank text,
  obtain_place text,
  note text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (success_rate is null or (success_rate between 0 and 100)),
  check (sort_order >= 0)
);

create table if not exists new_axe_net.info_craft_materials (
  id bigint generated by default as identity primary key,
  legacy_key text not null unique,
  craft_id text not null references new_axe_net.info_crafts(id) on delete cascade,
  material_name text not null,
  quantity numeric(12,2) not null default 0,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (quantity >= 0),
  check (sort_order >= 0)
);

create table if not exists new_axe_net.info_material_recipes (
  id bigint generated by default as identity primary key,
  legacy_key text not null unique,
  item_name text not null,
  input1 text,
  input1_qty numeric(12,2) not null default 0,
  input2 text,
  input2_qty numeric(12,2) not null default 0,
  input3 text,
  input3_qty numeric(12,2) not null default 0,
  note text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (input1_qty >= 0 and input2_qty >= 0 and input3_qty >= 0),
  check (sort_order >= 0)
);

create table if not exists new_axe_net.info_quests (
  id bigint generated by default as identity primary key,
  legacy_key text not null unique,
  job text not null,
  item_name text not null,
  required_qty numeric(12,2) not null default 0,
  reward_money integer not null default 0,
  reward_xp integer,
  rank text,
  note text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (required_qty >= 0),
  check (reward_money >= 0),
  check (reward_xp is null or reward_xp >= 0),
  check (sort_order >= 0)
);

create table if not exists new_axe_net.info_processes (
  id bigint generated by default as identity primary key,
  legacy_key text not null unique,
  job text not null,
  process_type text not null,
  item_name text not null,
  input1 text,
  input1_qty numeric(12,2) not null default 0,
  input2 text,
  input2_qty numeric(12,2) not null default 0,
  output_qty numeric(12,2) not null default 0,
  quest_qty numeric(12,2) not null default 0,
  reward_money integer not null default 0,
  reward_xp integer,
  rank text,
  note text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (input1_qty >= 0 and input2_qty >= 0 and output_qty >= 0 and quest_qty >= 0),
  check (reward_money >= 0 and reward_xp >= 0),
  check (sort_order >= 0)
);

create table if not exists new_axe_net.info_modbooks (
  id bigint generated by default as identity primary key,
  legacy_key text unique,
  type text not null check (type in ('접두', '접미')),
  category text not null,
  name text not null,
  parts text not null default '',
  option1 text,
  option2 text,
  option3 text,
  success_rate integer,
  note text,
  sort_order integer not null default 0,
  recent_price integer,
  recent_date date,
  price_note text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (success_rate is null or (success_rate between 0 and 100)),
  check (recent_price is null or recent_price >= 0),
  check (sort_order >= 0)
);

create table if not exists new_axe_net.info_skill_ranks (
  id bigint generated by default as identity primary key,
  legacy_key text not null unique,
  skill text not null,
  rank text not null,
  required_point numeric(12,2) not null default 0,
  point_type text,
  note text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (required_point >= 0),
  check (sort_order >= 0)
);

-- 개조서 등록 신청은 멤버 웹 세션을 검증한 Vercel API가 service_role로 기록합니다.
create table if not exists new_axe_net.info_modbook_requests (
  id bigint generated by default as identity primary key,
  member_key text not null references new_axe_net.members(member_key) on delete restrict,
  nickname text not null,
  type text not null check (type in ('접두', '접미')),
  category text not null,
  name text not null,
  parts text not null default '',
  option1 text,
  option2 text,
  option3 text,
  success_rate integer,
  note text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  review_note text,
  reviewer text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (success_rate is null or (success_rate between 0 and 100))
);

create unique index if not exists info_modbook_requests_pending_unique
  on new_axe_net.info_modbook_requests (member_key, type, category, name)
  where status = 'pending';

create index if not exists info_crafts_category_order_idx
  on new_axe_net.info_crafts (category, sort_order, item_name);
create index if not exists info_craft_materials_craft_order_idx
  on new_axe_net.info_craft_materials (craft_id, sort_order, id);
create index if not exists info_quests_job_order_idx
  on new_axe_net.info_quests (job, sort_order, id);
create index if not exists info_processes_job_order_idx
  on new_axe_net.info_processes (job, sort_order, id);
create index if not exists info_modbooks_type_category_order_idx
  on new_axe_net.info_modbooks (active, type, category, sort_order, id);
create index if not exists info_skill_ranks_skill_order_idx
  on new_axe_net.info_skill_ranks (skill, sort_order, id);
create index if not exists info_modbook_requests_status_created_idx
  on new_axe_net.info_modbook_requests (status, created_at desc);

-- updated_at은 기존 공통 함수 사용
DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'info_crafts','info_craft_materials','info_material_recipes','info_quests',
    'info_processes','info_modbooks','info_skill_ranks','info_modbook_requests'
  ] LOOP
    EXECUTE format('drop trigger if exists %I on new_axe_net.%I', t || '_touch_updated_at', t);
    EXECUTE format(
      'create trigger %I before update on new_axe_net.%I for each row execute function new_axe_net.touch_updated_at()',
      t || '_touch_updated_at', t
    );
  END LOOP;
END $$;

-- =========================================================
-- 2) 공개 조회 뷰
-- =========================================================

create or replace view new_axe_net.info_crafts_app
with (security_invoker = false)
as
select id, category, item_name, success_rate, craft_rank, obtain_place, note, sort_order
from new_axe_net.info_crafts;

create or replace view new_axe_net.info_craft_materials_app
with (security_invoker = false)
as
select id, craft_id, material_name, quantity, sort_order
from new_axe_net.info_craft_materials;

create or replace view new_axe_net.info_material_recipes_app
with (security_invoker = false)
as
select id, item_name, input1, input1_qty, input2, input2_qty, input3, input3_qty, note, sort_order
from new_axe_net.info_material_recipes;

create or replace view new_axe_net.info_quests_app
with (security_invoker = false)
as
select id, job, item_name, required_qty, reward_money, reward_xp, rank, note, sort_order
from new_axe_net.info_quests;

create or replace view new_axe_net.info_processes_app
with (security_invoker = false)
as
select id, job, process_type, item_name, input1, input1_qty, input2, input2_qty,
       output_qty, quest_qty, reward_money, reward_xp, rank, note, sort_order
from new_axe_net.info_processes;

create or replace view new_axe_net.info_modbooks_app
with (security_invoker = false)
as
select id, type, category, name, parts, option1, option2, option3, success_rate, note,
       sort_order, recent_price, recent_date, price_note, updated_at
from new_axe_net.info_modbooks
where active = true;

create or replace view new_axe_net.info_skill_ranks_app
with (security_invoker = false)
as
select id, skill, rank, required_point, point_type, note, sort_order
from new_axe_net.info_skill_ranks;

revoke all on new_axe_net.info_crafts_app from public;
revoke all on new_axe_net.info_craft_materials_app from public;
revoke all on new_axe_net.info_material_recipes_app from public;
revoke all on new_axe_net.info_quests_app from public;
revoke all on new_axe_net.info_processes_app from public;
revoke all on new_axe_net.info_modbooks_app from public;
revoke all on new_axe_net.info_skill_ranks_app from public;

grant select on new_axe_net.info_crafts_app to anon, authenticated;
grant select on new_axe_net.info_craft_materials_app to anon, authenticated;
grant select on new_axe_net.info_material_recipes_app to anon, authenticated;
grant select on new_axe_net.info_quests_app to anon, authenticated;
grant select on new_axe_net.info_processes_app to anon, authenticated;
grant select on new_axe_net.info_modbooks_app to anon, authenticated;
grant select on new_axe_net.info_skill_ranks_app to anon, authenticated;

-- =========================================================
-- 3) RLS / 권한
-- =========================================================

alter table new_axe_net.info_crafts enable row level security;
alter table new_axe_net.info_craft_materials enable row level security;
alter table new_axe_net.info_material_recipes enable row level security;
alter table new_axe_net.info_quests enable row level security;
alter table new_axe_net.info_processes enable row level security;
alter table new_axe_net.info_modbooks enable row level security;
alter table new_axe_net.info_skill_ranks enable row level security;
alter table new_axe_net.info_modbook_requests enable row level security;

revoke all on table new_axe_net.info_crafts from anon, authenticated;
revoke all on table new_axe_net.info_craft_materials from anon, authenticated;
revoke all on table new_axe_net.info_material_recipes from anon, authenticated;
revoke all on table new_axe_net.info_quests from anon, authenticated;
revoke all on table new_axe_net.info_processes from anon, authenticated;
revoke all on table new_axe_net.info_modbooks from anon, authenticated;
revoke all on table new_axe_net.info_skill_ranks from anon, authenticated;
revoke all on table new_axe_net.info_modbook_requests from anon, authenticated;

grant select on table new_axe_net.info_modbook_requests to authenticated;
grant select, insert on table new_axe_net.info_modbook_requests to service_role;
grant select, insert, update on table new_axe_net.info_modbooks to service_role;
grant usage, select on all sequences in schema new_axe_net to service_role;

drop policy if exists info_modbook_requests_admin_read on new_axe_net.info_modbook_requests;
create policy info_modbook_requests_admin_read
on new_axe_net.info_modbook_requests
for select to authenticated
using (new_axe_net.is_admin());

-- =========================================================
-- 4) 관리자 표시명
-- =========================================================

create or replace function new_axe_net.info_actor_nickname()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select m.nickname
  from new_axe_net.admin_accounts a
  join new_axe_net.members m on m.member_key = a.member_key
  where a.user_id = auth.uid()
    and a.enabled = true
  limit 1;
$$;

revoke all on function new_axe_net.info_actor_nickname() from public, anon;
grant execute on function new_axe_net.info_actor_nickname() to authenticated;

-- =========================================================
-- 5) 관리자 개조서 저장
-- =========================================================

create or replace function new_axe_net.save_info_modbook(
  p_id bigint,
  p_type text,
  p_category text,
  p_name text,
  p_parts text,
  p_option1 text,
  p_option2 text,
  p_option3 text,
  p_success_rate integer,
  p_note text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id bigint;
  v_type text := btrim(coalesce(p_type, ''));
  v_category text := nullif(btrim(coalesce(p_category, '')), '');
  v_name text := nullif(btrim(coalesce(p_name, '')), '');
  v_parts text := btrim(coalesce(p_parts, ''));
  v_order integer;
begin
  if not new_axe_net.is_admin() then
    raise exception '관리자 권한이 필요합니다.' using errcode = '42501';
  end if;
  if v_type not in ('접두','접미') then
    raise exception '개조 위치는 접두 또는 접미여야 합니다.' using errcode = '22023';
  end if;
  if v_category is null or v_name is null then
    raise exception '분류와 개조서 이름을 입력하세요.' using errcode = '22023';
  end if;
  if p_success_rate is not null and (p_success_rate < 0 or p_success_rate > 100) then
    raise exception '성공률은 0~100 사이로 입력하세요.' using errcode = '22023';
  end if;

  if p_id is null then
    select coalesce(max(sort_order), 0) + 1
      into v_order
    from new_axe_net.info_modbooks
    where type = v_type and category = v_category;

    insert into new_axe_net.info_modbooks (
      type, category, name, parts, option1, option2, option3,
      success_rate, note, sort_order, active
    ) values (
      v_type, v_category, v_name, v_parts,
      nullif(btrim(coalesce(p_option1,'')), ''),
      nullif(btrim(coalesce(p_option2,'')), ''),
      nullif(btrim(coalesce(p_option3,'')), ''),
      p_success_rate,
      nullif(btrim(coalesce(p_note,'')), ''),
      v_order,
      true
    ) returning id into v_id;
  else
    update new_axe_net.info_modbooks
       set type = v_type,
           category = v_category,
           name = v_name,
           parts = v_parts,
           option1 = nullif(btrim(coalesce(p_option1,'')), ''),
           option2 = nullif(btrim(coalesce(p_option2,'')), ''),
           option3 = nullif(btrim(coalesce(p_option3,'')), ''),
           success_rate = p_success_rate,
           note = nullif(btrim(coalesce(p_note,'')), ''),
           active = true
     where id = p_id
     returning id into v_id;

    if v_id is null then
      raise exception '수정할 개조서를 찾을 수 없습니다.' using errcode = 'P0002';
    end if;
  end if;

  return v_id;
end;
$$;

create or replace function new_axe_net.update_info_modbook_price(
  p_id bigint,
  p_recent_price integer,
  p_price_note text default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id bigint;
  v_actor text;
begin
  if not new_axe_net.is_admin() then
    raise exception '관리자 권한이 필요합니다.' using errcode = '42501';
  end if;
  if p_recent_price is not null and p_recent_price < 0 then
    raise exception '최근 거래가는 0 이상으로 입력하세요.' using errcode = '22023';
  end if;

  v_actor := coalesce(new_axe_net.info_actor_nickname(), 'ADMIN');

  update new_axe_net.info_modbooks
     set recent_price = p_recent_price,
         recent_date = case when p_recent_price is null then null else (now() at time zone 'Asia/Seoul')::date end,
         price_note = case
           when p_recent_price is null then null
           else coalesce(nullif(btrim(coalesce(p_price_note,'')), ''), v_actor)
         end
   where id = p_id and active = true
   returning id into v_id;

  if v_id is null then
    raise exception '개조서를 찾을 수 없습니다.' using errcode = 'P0002';
  end if;
  return v_id;
end;
$$;

create or replace function new_axe_net.deactivate_info_modbook(p_id bigint)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count integer;
begin
  if not new_axe_net.is_admin() then
    raise exception '관리자 권한이 필요합니다.' using errcode = '42501';
  end if;

  update new_axe_net.info_modbooks
     set active = false
   where id = p_id and active = true;
  get diagnostics v_count = row_count;
  return v_count > 0;
end;
$$;

-- =========================================================
-- 6) 개조서 신청 승인 / 반려
-- =========================================================

create or replace function new_axe_net.review_info_modbook_request(
  p_request_id bigint,
  p_action text,
  p_review_note text default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_request new_axe_net.info_modbook_requests%rowtype;
  v_action text := lower(btrim(coalesce(p_action,'')));
  v_actor text;
  v_modbook_id bigint := null;
  v_order integer;
begin
  if not new_axe_net.is_admin() then
    raise exception '관리자 권한이 필요합니다.' using errcode = '42501';
  end if;
  if v_action not in ('approve','reject') then
    raise exception '승인 또는 반려 작업만 지원합니다.' using errcode = '22023';
  end if;

  select * into v_request
  from new_axe_net.info_modbook_requests
  where id = p_request_id
  for update;

  if not found then
    raise exception '신청 내역을 찾을 수 없습니다.' using errcode = 'P0002';
  end if;
  if v_request.status <> 'pending' then
    raise exception '이미 처리된 신청입니다.' using errcode = '22023';
  end if;

  v_actor := coalesce(new_axe_net.info_actor_nickname(), 'ADMIN');

  if v_action = 'approve' then
    select coalesce(max(sort_order), 0) + 1
      into v_order
    from new_axe_net.info_modbooks
    where type = v_request.type and category = v_request.category;

    insert into new_axe_net.info_modbooks (
      type, category, name, parts, option1, option2, option3,
      success_rate, note, sort_order, active
    ) values (
      v_request.type, v_request.category, v_request.name, v_request.parts,
      v_request.option1, v_request.option2, v_request.option3,
      v_request.success_rate, v_request.note, v_order, true
    ) returning id into v_modbook_id;

    update new_axe_net.info_modbook_requests
       set status = 'approved',
           review_note = nullif(btrim(coalesce(p_review_note,'')), ''),
           reviewer = v_actor,
           reviewed_at = now()
     where id = p_request_id;
  else
    update new_axe_net.info_modbook_requests
       set status = 'rejected',
           review_note = nullif(btrim(coalesce(p_review_note,'')), ''),
           reviewer = v_actor,
           reviewed_at = now()
     where id = p_request_id;
  end if;

  return coalesce(v_modbook_id, p_request_id);
end;
$$;

-- =========================================================
-- 7) 함수 실행 권한
-- =========================================================

revoke all on function new_axe_net.save_info_modbook(bigint,text,text,text,text,text,text,text,integer,text) from public, anon;
grant execute on function new_axe_net.save_info_modbook(bigint,text,text,text,text,text,text,text,integer,text) to authenticated;

revoke all on function new_axe_net.update_info_modbook_price(bigint,integer,text) from public, anon;
grant execute on function new_axe_net.update_info_modbook_price(bigint,integer,text) to authenticated;

revoke all on function new_axe_net.deactivate_info_modbook(bigint) from public, anon;
grant execute on function new_axe_net.deactivate_info_modbook(bigint) to authenticated;

revoke all on function new_axe_net.review_info_modbook_request(bigint,text,text) from public, anon;
grant execute on function new_axe_net.review_info_modbook_request(bigint,text,text) to authenticated;

notify pgrst, 'reload schema';
