-- AXE NET v1.28.0
-- 026_assets_plika.sql
-- 회사자산 + 플리카 계좌 Supabase-native 전환
-- 전제: 001 ~ 025 적용 완료
--
-- 보안 기준
-- - 회사자산/반납내역: 관리자만 브라우저에서 조회/관리
-- - 플리카 계좌: anon 공개 금지. 일반 멤버는 Vercel member-session 서버를 통해 조회
-- - 플리카 신청: 일반 멤버는 member-session 서버가 service_role로 본인 신청만 등록
-- - 관리자 쓰기: Supabase Auth + is_admin() 검증 RPC
-- - 기존 public / Google Sheet는 런타임 경로로 사용하지 않음

create schema if not exists new_axe_net;
grant usage on schema new_axe_net to authenticated, service_role;

-- =========================================================
-- 1) 회사 자산
-- =========================================================

create table if not exists new_axe_net.company_assets (
  id bigint generated by default as identity primary key,
  legacy_no text,
  member_key text references new_axe_net.members(member_key) on update cascade on delete set null,
  owner_name text not null,
  asset_category text not null default '기타',
  asset_name text not null,
  acquisition_method text,
  acquired_at date,
  personal_cost bigint check (personal_cost is null or personal_cost >= 0),
  status text not null default '보유',
  note text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists company_assets_active_status_idx
  on new_axe_net.company_assets (active, status, sort_order, id);
create index if not exists company_assets_owner_idx
  on new_axe_net.company_assets (owner_name, active);
create index if not exists company_assets_member_key_idx
  on new_axe_net.company_assets (member_key);

drop trigger if exists company_assets_touch_updated_at on new_axe_net.company_assets;
create trigger company_assets_touch_updated_at
before update on new_axe_net.company_assets
for each row execute function new_axe_net.touch_updated_at();

-- =========================================================
-- 2) 퇴사자 / 자산 반납 내역
-- =========================================================

create table if not exists new_axe_net.company_asset_returns (
  id bigint generated by default as identity primary key,
  legacy_no text,
  asset_id bigint references new_axe_net.company_assets(id) on update cascade on delete set null,
  member_key text references new_axe_net.members(member_key) on update cascade on delete set null,
  owner_name text not null,
  asset_name text not null,
  returned boolean not null default false,
  checker text,
  processed_at date,
  note text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists company_asset_returns_active_returned_idx
  on new_axe_net.company_asset_returns (active, returned, processed_at desc, id desc);
create index if not exists company_asset_returns_member_key_idx
  on new_axe_net.company_asset_returns (member_key);

drop trigger if exists company_asset_returns_touch_updated_at on new_axe_net.company_asset_returns;
create trigger company_asset_returns_touch_updated_at
before update on new_axe_net.company_asset_returns
for each row execute function new_axe_net.touch_updated_at();

-- =========================================================
-- 3) 플리카 계좌
-- =========================================================

create table if not exists new_axe_net.member_accounts (
  id bigint generated by default as identity primary key,
  member_key text not null unique references new_axe_net.members(member_key) on update cascade on delete cascade,
  account text not null,
  enabled boolean not null default true,
  note text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists member_accounts_enabled_order_idx
  on new_axe_net.member_accounts (enabled, sort_order, id);

drop trigger if exists member_accounts_touch_updated_at on new_axe_net.member_accounts;
create trigger member_accounts_touch_updated_at
before update on new_axe_net.member_accounts
for each row execute function new_axe_net.touch_updated_at();

-- =========================================================
-- 4) 플리카 계좌 등록/변경 신청
-- =========================================================

create table if not exists new_axe_net.member_account_requests (
  id bigint generated by default as identity primary key,
  member_key text not null references new_axe_net.members(member_key) on update cascade on delete cascade,
  nickname text not null,
  account text not null,
  note text,
  status text not null default 'pending'
    check (status in ('pending','approved','rejected')),
  reviewer text,
  review_note text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists member_account_requests_pending_unique
  on new_axe_net.member_account_requests (member_key)
  where status = 'pending';
create index if not exists member_account_requests_status_created_idx
  on new_axe_net.member_account_requests (status, created_at desc);

drop trigger if exists member_account_requests_touch_updated_at on new_axe_net.member_account_requests;
create trigger member_account_requests_touch_updated_at
before update on new_axe_net.member_account_requests
for each row execute function new_axe_net.touch_updated_at();

-- =========================================================
-- 5) RLS / 직접 접근 권한
-- =========================================================

alter table new_axe_net.company_assets enable row level security;
alter table new_axe_net.company_asset_returns enable row level security;
alter table new_axe_net.member_accounts enable row level security;
alter table new_axe_net.member_account_requests enable row level security;

revoke all on table new_axe_net.company_assets from anon, authenticated;
revoke all on table new_axe_net.company_asset_returns from anon, authenticated;
revoke all on table new_axe_net.member_accounts from anon, authenticated;
revoke all on table new_axe_net.member_account_requests from anon, authenticated;

-- 관리자 브라우저 조회용. RLS에서 is_admin()을 다시 검증합니다.
grant select on table new_axe_net.company_assets to authenticated;
grant select on table new_axe_net.company_asset_returns to authenticated;
grant select on table new_axe_net.member_accounts to authenticated;
grant select on table new_axe_net.member_account_requests to authenticated;

-- 멤버 세션 서버(Vercel) 전용
grant select, insert, update, delete on table new_axe_net.company_assets to service_role;
grant select, insert, update, delete on table new_axe_net.company_asset_returns to service_role;
grant select, insert, update, delete on table new_axe_net.member_accounts to service_role;
grant select, insert, update, delete on table new_axe_net.member_account_requests to service_role;
grant usage, select on all sequences in schema new_axe_net to service_role;

drop policy if exists company_assets_admin_read on new_axe_net.company_assets;
create policy company_assets_admin_read
on new_axe_net.company_assets for select to authenticated
using (new_axe_net.is_admin());

drop policy if exists company_asset_returns_admin_read on new_axe_net.company_asset_returns;
create policy company_asset_returns_admin_read
on new_axe_net.company_asset_returns for select to authenticated
using (new_axe_net.is_admin());

drop policy if exists member_accounts_admin_read on new_axe_net.member_accounts;
create policy member_accounts_admin_read
on new_axe_net.member_accounts for select to authenticated
using (new_axe_net.is_admin());

drop policy if exists member_account_requests_admin_read on new_axe_net.member_account_requests;
create policy member_account_requests_admin_read
on new_axe_net.member_account_requests for select to authenticated
using (new_axe_net.is_admin());

-- =========================================================
-- 6) 관리자 표시명
-- =========================================================

create or replace function new_axe_net.asset_actor_nickname()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select m.nickname
  from new_axe_net.admin_accounts a
  join new_axe_net.members m on m.member_key = a.member_key
  where a.user_id = auth.uid()
    and a.enabled = true
  limit 1;
$$;

revoke all on function new_axe_net.asset_actor_nickname() from public, anon;
grant execute on function new_axe_net.asset_actor_nickname() to authenticated;

-- =========================================================
-- 7) 회사 자산 관리자 RPC
-- =========================================================

create or replace function new_axe_net.save_company_asset(
  p_id bigint,
  p_legacy_no text,
  p_member_key text,
  p_owner_name text,
  p_asset_category text,
  p_asset_name text,
  p_acquisition_method text,
  p_acquired_at date,
  p_personal_cost bigint,
  p_status text,
  p_note text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id bigint;
  v_owner text := nullif(btrim(coalesce(p_owner_name,'')), '');
  v_asset text := nullif(btrim(coalesce(p_asset_name,'')), '');
  v_category text := coalesce(nullif(btrim(coalesce(p_asset_category,'')), ''), '기타');
  v_status text := coalesce(nullif(btrim(coalesce(p_status,'')), ''), '보유');
  v_order integer;
begin
  if not new_axe_net.is_admin() then
    raise exception '관리자 권한이 필요합니다.' using errcode='42501';
  end if;
  if v_owner is null or v_asset is null then
    raise exception '보유자와 자산명을 입력하세요.' using errcode='22023';
  end if;
  if p_personal_cost is not null and p_personal_cost < 0 then
    raise exception '개인 부담 비용은 0 이상이어야 합니다.' using errcode='22023';
  end if;
  if p_member_key is not null and not exists (
    select 1 from new_axe_net.members m where m.member_key = p_member_key
  ) then
    raise exception '연결할 멤버를 찾을 수 없습니다.' using errcode='22023';
  end if;

  if p_id is null then
    select coalesce(max(sort_order),0)+1 into v_order from new_axe_net.company_assets;
    insert into new_axe_net.company_assets (
      legacy_no,member_key,owner_name,asset_category,asset_name,acquisition_method,
      acquired_at,personal_cost,status,note,active,sort_order
    ) values (
      nullif(btrim(coalesce(p_legacy_no,'')),''),p_member_key,v_owner,v_category,v_asset,
      nullif(btrim(coalesce(p_acquisition_method,'')),''),p_acquired_at,p_personal_cost,v_status,
      nullif(btrim(coalesce(p_note,'')),''),true,v_order
    ) returning id into v_id;
  else
    update new_axe_net.company_assets
       set legacy_no = nullif(btrim(coalesce(p_legacy_no,'')),''),
           member_key = p_member_key,
           owner_name = v_owner,
           asset_category = v_category,
           asset_name = v_asset,
           acquisition_method = nullif(btrim(coalesce(p_acquisition_method,'')),''),
           acquired_at = p_acquired_at,
           personal_cost = p_personal_cost,
           status = v_status,
           note = nullif(btrim(coalesce(p_note,'')),''),
           active = true
     where id = p_id
     returning id into v_id;
    if v_id is null then raise exception '수정할 자산을 찾을 수 없습니다.' using errcode='P0002'; end if;
  end if;
  return v_id;
end;
$$;

create or replace function new_axe_net.deactivate_company_asset(p_id bigint)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare v_count integer;
begin
  if not new_axe_net.is_admin() then raise exception '관리자 권한이 필요합니다.' using errcode='42501'; end if;
  update new_axe_net.company_assets set active=false where id=p_id and active=true;
  get diagnostics v_count = row_count;
  return v_count > 0;
end;
$$;

create or replace function new_axe_net.save_company_asset_return(
  p_id bigint,
  p_legacy_no text,
  p_asset_id bigint,
  p_member_key text,
  p_owner_name text,
  p_asset_name text,
  p_returned boolean,
  p_checker text,
  p_processed_at date,
  p_note text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id bigint;
  v_owner text := nullif(btrim(coalesce(p_owner_name,'')), '');
  v_asset text := nullif(btrim(coalesce(p_asset_name,'')), '');
  v_checker text := nullif(btrim(coalesce(p_checker,'')), '');
begin
  if not new_axe_net.is_admin() then raise exception '관리자 권한이 필요합니다.' using errcode='42501'; end if;
  if v_owner is null or v_asset is null then raise exception '이름과 자산명을 입력하세요.' using errcode='22023'; end if;
  if p_asset_id is not null and not exists (select 1 from new_axe_net.company_assets a where a.id=p_asset_id) then
    raise exception '연결할 자산을 찾을 수 없습니다.' using errcode='22023';
  end if;
  if p_member_key is not null and not exists (select 1 from new_axe_net.members m where m.member_key=p_member_key) then
    raise exception '연결할 멤버를 찾을 수 없습니다.' using errcode='22023';
  end if;

  if coalesce(p_returned,false) and v_checker is null then
    v_checker := coalesce(new_axe_net.asset_actor_nickname(), 'ADMIN');
  end if;

  if p_id is null then
    insert into new_axe_net.company_asset_returns (
      legacy_no,asset_id,member_key,owner_name,asset_name,returned,checker,processed_at,note,active
    ) values (
      nullif(btrim(coalesce(p_legacy_no,'')),''),p_asset_id,p_member_key,v_owner,v_asset,
      coalesce(p_returned,false),v_checker,
      case when coalesce(p_returned,false) then coalesce(p_processed_at,(now() at time zone 'Asia/Seoul')::date) else p_processed_at end,
      nullif(btrim(coalesce(p_note,'')),''),true
    ) returning id into v_id;
  else
    update new_axe_net.company_asset_returns
       set legacy_no=nullif(btrim(coalesce(p_legacy_no,'')),''),
           asset_id=p_asset_id,
           member_key=p_member_key,
           owner_name=v_owner,
           asset_name=v_asset,
           returned=coalesce(p_returned,false),
           checker=v_checker,
           processed_at=case when coalesce(p_returned,false) then coalesce(p_processed_at,processed_at,(now() at time zone 'Asia/Seoul')::date) else p_processed_at end,
           note=nullif(btrim(coalesce(p_note,'')),''),
           active=true
     where id=p_id
     returning id into v_id;
    if v_id is null then raise exception '수정할 반납 내역을 찾을 수 없습니다.' using errcode='P0002'; end if;
  end if;
  return v_id;
end;
$$;

create or replace function new_axe_net.deactivate_company_asset_return(p_id bigint)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare v_count integer;
begin
  if not new_axe_net.is_admin() then raise exception '관리자 권한이 필요합니다.' using errcode='42501'; end if;
  update new_axe_net.company_asset_returns set active=false where id=p_id and active=true;
  get diagnostics v_count = row_count;
  return v_count > 0;
end;
$$;

-- =========================================================
-- 8) 플리카 계좌 관리자 RPC
-- =========================================================

create or replace function new_axe_net.save_member_account(
  p_member_key text,
  p_account text,
  p_enabled boolean default true,
  p_note text default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id bigint;
  v_account text := nullif(btrim(coalesce(p_account,'')), '');
  v_order integer;
begin
  if not new_axe_net.is_admin() then raise exception '관리자 권한이 필요합니다.' using errcode='42501'; end if;
  if p_member_key is null or not exists (select 1 from new_axe_net.members m where m.member_key=p_member_key) then
    raise exception '멤버를 선택하세요.' using errcode='22023';
  end if;
  if v_account is null then raise exception '계좌번호를 입력하세요.' using errcode='22023'; end if;
  if length(v_account) > 100 then raise exception '계좌번호가 너무 깁니다.' using errcode='22023'; end if;

  select sort_order into v_order from new_axe_net.member_accounts where member_key=p_member_key;
  if v_order is null then select coalesce(max(sort_order),0)+1 into v_order from new_axe_net.member_accounts; end if;

  insert into new_axe_net.member_accounts (member_key,account,enabled,note,sort_order)
  values (p_member_key,v_account,coalesce(p_enabled,true),nullif(btrim(coalesce(p_note,'')),''),v_order)
  on conflict (member_key) do update
    set account=excluded.account,
        enabled=excluded.enabled,
        note=excluded.note
  returning id into v_id;
  return v_id;
end;
$$;

create or replace function new_axe_net.deactivate_member_account(p_member_key text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare v_count integer;
begin
  if not new_axe_net.is_admin() then raise exception '관리자 권한이 필요합니다.' using errcode='42501'; end if;
  update new_axe_net.member_accounts set enabled=false where member_key=p_member_key and enabled=true;
  get diagnostics v_count = row_count;
  return v_count > 0;
end;
$$;

create or replace function new_axe_net.review_member_account_request(
  p_request_id bigint,
  p_action text,
  p_review_note text default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_request new_axe_net.member_account_requests%rowtype;
  v_action text := lower(btrim(coalesce(p_action,'')));
  v_actor text;
  v_account_id bigint := null;
  v_order integer;
begin
  if not new_axe_net.is_admin() then raise exception '관리자 권한이 필요합니다.' using errcode='42501'; end if;
  if v_action not in ('approve','reject') then raise exception '승인 또는 반려 작업만 지원합니다.' using errcode='22023'; end if;

  select * into v_request from new_axe_net.member_account_requests where id=p_request_id for update;
  if not found then raise exception '신청 내역을 찾을 수 없습니다.' using errcode='P0002'; end if;
  if v_request.status <> 'pending' then raise exception '이미 처리된 신청입니다.' using errcode='22023'; end if;

  v_actor := coalesce(new_axe_net.asset_actor_nickname(),'ADMIN');

  if v_action='approve' then
    select sort_order into v_order from new_axe_net.member_accounts where member_key=v_request.member_key;
    if v_order is null then select coalesce(max(sort_order),0)+1 into v_order from new_axe_net.member_accounts; end if;

    insert into new_axe_net.member_accounts (member_key,account,enabled,note,sort_order)
    values (v_request.member_key,v_request.account,true,v_request.note,v_order)
    on conflict (member_key) do update
      set account=excluded.account, enabled=true, note=excluded.note
    returning id into v_account_id;

    update new_axe_net.member_account_requests
       set status='approved', reviewer=v_actor,
           review_note=nullif(btrim(coalesce(p_review_note,'')),''), reviewed_at=now()
     where id=p_request_id;
  else
    update new_axe_net.member_account_requests
       set status='rejected', reviewer=v_actor,
           review_note=nullif(btrim(coalesce(p_review_note,'')),''), reviewed_at=now()
     where id=p_request_id;
  end if;

  return coalesce(v_account_id,p_request_id);
end;
$$;

-- =========================================================
-- 9) RPC 실행 권한
-- =========================================================

revoke all on function new_axe_net.save_company_asset(bigint,text,text,text,text,text,text,date,bigint,text,text) from public, anon;
grant execute on function new_axe_net.save_company_asset(bigint,text,text,text,text,text,text,date,bigint,text,text) to authenticated;

revoke all on function new_axe_net.deactivate_company_asset(bigint) from public, anon;
grant execute on function new_axe_net.deactivate_company_asset(bigint) to authenticated;

revoke all on function new_axe_net.save_company_asset_return(bigint,text,bigint,text,text,text,boolean,text,date,text) from public, anon;
grant execute on function new_axe_net.save_company_asset_return(bigint,text,bigint,text,text,text,boolean,text,date,text) to authenticated;

revoke all on function new_axe_net.deactivate_company_asset_return(bigint) from public, anon;
grant execute on function new_axe_net.deactivate_company_asset_return(bigint) to authenticated;

revoke all on function new_axe_net.save_member_account(text,text,boolean,text) from public, anon;
grant execute on function new_axe_net.save_member_account(text,text,boolean,text) to authenticated;

revoke all on function new_axe_net.deactivate_member_account(text) from public, anon;
grant execute on function new_axe_net.deactivate_member_account(text) to authenticated;

revoke all on function new_axe_net.review_member_account_request(bigint,text,text) from public, anon;
grant execute on function new_axe_net.review_member_account_request(bigint,text,text) to authenticated;

notify pgrst, 'reload schema';
