-- NEW AXE NET v1.29.0
-- 030_outlaw_module.sql
-- AXE WAR Supabase 프로젝트 > SQL Editor에서 전체 실행
--
-- NEW AXE NET 무법지대 모듈 기반 스키마
-- - 현재 무법지대 통계
-- - 통계 기록 히스토리
-- - 무법지대 공략(지역 + 단계)
-- - 브리핑맵
--
-- 보안 원칙
-- - anon 직접 조회 금지
-- - 일반 멤버는 HttpOnly member session -> Vercel server(service_role) 경로로 조회
-- - Supabase authenticated 직접 조회는 NEW AXE NET 관리자만 허용
-- - Google Sheet / Apps Script 런타임 의존 없음

create schema if not exists new_axe_net;
grant usage on schema new_axe_net to authenticated, service_role;

-- =========================================================
-- 1) 현재 무법지대 통계
-- =========================================================

create table if not exists new_axe_net.outlaw_stats_current (
  id bigint generated by default as identity primary key,
  member_key text not null unique
    references new_axe_net.members(member_key)
    on update cascade on delete cascade,
  source_nickname text not null,
  discord_user_id text not null unique,
  total_kills integer not null default 0 check (total_kills >= 0),
  total_deaths integer not null default 0 check (total_deaths >= 0),
  kd numeric(10,2) generated always as (
    case
      when total_deaths = 0 then total_kills::numeric
      else round(total_kills::numeric / total_deaths::numeric, 2)
    end
  ) stored,
  last_message_id text,
  source_image_url text,
  source_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists outlaw_stats_current_rank_idx
  on new_axe_net.outlaw_stats_current
  (total_kills desc, kd desc, total_deaths asc);

create index if not exists outlaw_stats_current_updated_idx
  on new_axe_net.outlaw_stats_current (source_updated_at desc);

drop trigger if exists outlaw_stats_current_touch_updated_at
on new_axe_net.outlaw_stats_current;

create trigger outlaw_stats_current_touch_updated_at
before update on new_axe_net.outlaw_stats_current
for each row
execute function new_axe_net.touch_updated_at();


-- =========================================================
-- 2) 무법지대 통계 기록
-- =========================================================

create table if not exists new_axe_net.outlaw_stats_history (
  record_id text primary key,
  member_key text not null
    references new_axe_net.members(member_key)
    on update cascade on delete cascade,
  source_nickname text not null,
  total_kills integer not null check (total_kills >= 0),
  total_deaths integer not null check (total_deaths >= 0),
  kill_delta integer not null default 0 check (kill_delta >= 0),
  death_delta integer not null default 0 check (death_delta >= 0),
  delta_kd numeric(10,2) not null default 0,
  channel_id text,
  discord_user_id text,
  message_id text,
  source_image_url text,
  confidence numeric(5,2),
  status text not null default 'approved'
    check (status in ('approved','pending','rejected')),
  recorded_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists outlaw_stats_history_member_recorded_idx
  on new_axe_net.outlaw_stats_history (member_key, recorded_at desc);

create index if not exists outlaw_stats_history_recorded_idx
  on new_axe_net.outlaw_stats_history (recorded_at desc);

create unique index if not exists outlaw_stats_history_message_unique
  on new_axe_net.outlaw_stats_history (message_id)
  where message_id is not null;


-- =========================================================
-- 3) 무법지대 공략 지역
-- =========================================================

create table if not exists new_axe_net.outlaw_guide_locations (
  location_key text primary key,
  map_name text not null,
  main_image text,
  coord text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists outlaw_guide_locations_active_order_idx
  on new_axe_net.outlaw_guide_locations (active, sort_order, location_key);

drop trigger if exists outlaw_guide_locations_touch_updated_at
on new_axe_net.outlaw_guide_locations;

create trigger outlaw_guide_locations_touch_updated_at
before update on new_axe_net.outlaw_guide_locations
for each row
execute function new_axe_net.touch_updated_at();


-- =========================================================
-- 4) 무법지대 공략 단계
-- =========================================================

create table if not exists new_axe_net.outlaw_guide_steps (
  id bigint generated by default as identity primary key,
  location_key text not null
    references new_axe_net.outlaw_guide_locations(location_key)
    on update cascade on delete cascade,
  route_group text not null default '기본 루트',
  step_no text not null,
  title text not null,
  content text,
  image text,
  video_url text,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (location_key, route_group, step_no)
);

create index if not exists outlaw_guide_steps_location_order_idx
  on new_axe_net.outlaw_guide_steps
  (location_key, active, sort_order, id);

drop trigger if exists outlaw_guide_steps_touch_updated_at
on new_axe_net.outlaw_guide_steps;

create trigger outlaw_guide_steps_touch_updated_at
before update on new_axe_net.outlaw_guide_steps
for each row
execute function new_axe_net.touch_updated_at();


-- =========================================================
-- 5) 브리핑맵
-- =========================================================

create table if not exists new_axe_net.outlaw_briefing_maps (
  map_key text primary key,
  map_name text not null,
  image text,
  description text,
  note text,
  coord text,
  source_updated_at date,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists outlaw_briefing_maps_active_order_idx
  on new_axe_net.outlaw_briefing_maps (active, sort_order, map_key);

drop trigger if exists outlaw_briefing_maps_touch_updated_at
on new_axe_net.outlaw_briefing_maps;

create trigger outlaw_briefing_maps_touch_updated_at
before update on new_axe_net.outlaw_briefing_maps
for each row
execute function new_axe_net.touch_updated_at();


-- =========================================================
-- 6) RLS / 권한
-- =========================================================

alter table new_axe_net.outlaw_stats_current enable row level security;
alter table new_axe_net.outlaw_stats_history enable row level security;
alter table new_axe_net.outlaw_guide_locations enable row level security;
alter table new_axe_net.outlaw_guide_steps enable row level security;
alter table new_axe_net.outlaw_briefing_maps enable row level security;

revoke all on table new_axe_net.outlaw_stats_current
from public, anon, authenticated;
revoke all on table new_axe_net.outlaw_stats_history
from public, anon, authenticated;
revoke all on table new_axe_net.outlaw_guide_locations
from public, anon, authenticated;
revoke all on table new_axe_net.outlaw_guide_steps
from public, anon, authenticated;
revoke all on table new_axe_net.outlaw_briefing_maps
from public, anon, authenticated;

grant select on table new_axe_net.outlaw_stats_current to authenticated;
grant select on table new_axe_net.outlaw_stats_history to authenticated;
grant select on table new_axe_net.outlaw_guide_locations to authenticated;
grant select on table new_axe_net.outlaw_guide_steps to authenticated;
grant select on table new_axe_net.outlaw_briefing_maps to authenticated;

grant select, insert, update, delete
on table new_axe_net.outlaw_stats_current to service_role;
grant select, insert, update, delete
on table new_axe_net.outlaw_stats_history to service_role;
grant select, insert, update, delete
on table new_axe_net.outlaw_guide_locations to service_role;
grant select, insert, update, delete
on table new_axe_net.outlaw_guide_steps to service_role;
grant select, insert, update, delete
on table new_axe_net.outlaw_briefing_maps to service_role;

grant usage, select on all sequences
in schema new_axe_net to service_role;

drop policy if exists outlaw_stats_current_admin_read
on new_axe_net.outlaw_stats_current;
create policy outlaw_stats_current_admin_read
on new_axe_net.outlaw_stats_current
for select to authenticated
using (new_axe_net.is_admin());

drop policy if exists outlaw_stats_history_admin_read
on new_axe_net.outlaw_stats_history;
create policy outlaw_stats_history_admin_read
on new_axe_net.outlaw_stats_history
for select to authenticated
using (new_axe_net.is_admin());

drop policy if exists outlaw_guide_locations_admin_read
on new_axe_net.outlaw_guide_locations;
create policy outlaw_guide_locations_admin_read
on new_axe_net.outlaw_guide_locations
for select to authenticated
using (new_axe_net.is_admin());

drop policy if exists outlaw_guide_steps_admin_read
on new_axe_net.outlaw_guide_steps;
create policy outlaw_guide_steps_admin_read
on new_axe_net.outlaw_guide_steps
for select to authenticated
using (new_axe_net.is_admin());

drop policy if exists outlaw_briefing_maps_admin_read
on new_axe_net.outlaw_briefing_maps;
create policy outlaw_briefing_maps_admin_read
on new_axe_net.outlaw_briefing_maps
for select to authenticated
using (new_axe_net.is_admin());

notify pgrst, 'reload schema';
