-- NEW AXE NET v1.35.0
-- 039_tube_comments.sql
-- AXE TUBE 댓글 기능
-- 전제: 033 ~ 038 적용 완료
--
-- 원칙
-- - 댓글 작성/수정/삭제는 NEW AXE NET 멤버 세션을 기준으로 처리합니다.
-- - 공개 화면에서는 활성 영상의 활성 댓글만 조회합니다.
-- - 멤버는 본인 댓글만 수정/삭제할 수 있습니다.
-- - 관리자는 댓글을 삭제(숨김)할 수 있습니다.
-- - 기존 AXE_TUBE.csv에는 댓글 원본이 없었으므로 과거 댓글을 임의 생성/이관하지 않습니다.

alter table new_axe_net.tube_videos
  add column if not exists comment_count integer not null default 0;

alter table new_axe_net.tube_videos
  drop constraint if exists tube_videos_comment_count_check;

alter table new_axe_net.tube_videos
  add constraint tube_videos_comment_count_check
  check (comment_count >= 0);

create table if not exists new_axe_net.tube_comments (
  id bigint generated by default as identity primary key,
  tube_id text not null
    references new_axe_net.tube_videos(tube_id)
    on update cascade on delete cascade,
  member_key text not null
    references new_axe_net.members(member_key)
    on update cascade on delete restrict,
  author_name text not null,
  author_badge text,
  body text not null,
  edited_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tube_comments_body_length_check
    check (char_length(btrim(body)) between 1 and 500)
);

create index if not exists tube_comments_tube_active_created_idx
  on new_axe_net.tube_comments(tube_id, active, created_at asc);

create index if not exists tube_comments_member_idx
  on new_axe_net.tube_comments(member_key, updated_at desc);

drop trigger if exists tube_comments_touch_updated_at
on new_axe_net.tube_comments;

create trigger tube_comments_touch_updated_at
before update on new_axe_net.tube_comments
for each row
execute function new_axe_net.touch_updated_at();

alter table new_axe_net.tube_comments enable row level security;

revoke all on table new_axe_net.tube_comments
from public, anon, authenticated;

grant select on table new_axe_net.tube_comments
to anon, authenticated;

grant select, insert, update, delete
on table new_axe_net.tube_comments
to service_role;

grant usage, select
on sequence new_axe_net.tube_comments_id_seq
to service_role;

drop policy if exists tube_comments_public_read
on new_axe_net.tube_comments;

create policy tube_comments_public_read
on new_axe_net.tube_comments
for select to anon, authenticated
using (
  active = true
  and exists (
    select 1
    from new_axe_net.tube_videos v
    where v.tube_id = tube_comments.tube_id
      and v.active = true
  )
);

create or replace function new_axe_net.sync_tube_comment_count()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_old_tube_id text;
  v_new_tube_id text;
begin
  if tg_op in ('UPDATE', 'DELETE') then
    v_old_tube_id := old.tube_id;
  end if;

  if tg_op in ('INSERT', 'UPDATE') then
    v_new_tube_id := new.tube_id;
  end if;

  if v_old_tube_id is not null then
    update new_axe_net.tube_videos v
    set comment_count = (
      select count(*)::integer
      from new_axe_net.tube_comments c
      where c.tube_id = v_old_tube_id
        and c.active = true
    )
    where v.tube_id = v_old_tube_id;
  end if;

  if v_new_tube_id is not null
     and v_new_tube_id is distinct from v_old_tube_id then
    update new_axe_net.tube_videos v
    set comment_count = (
      select count(*)::integer
      from new_axe_net.tube_comments c
      where c.tube_id = v_new_tube_id
        and c.active = true
    )
    where v.tube_id = v_new_tube_id;
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists tube_comments_sync_count
on new_axe_net.tube_comments;

create trigger tube_comments_sync_count
after insert or update or delete on new_axe_net.tube_comments
for each row
execute function new_axe_net.sync_tube_comment_count();

-- 기존 값이 있더라도 현재 활성 댓글 기준으로 정확히 재계산합니다.
update new_axe_net.tube_videos v
set comment_count = (
  select count(*)::integer
  from new_axe_net.tube_comments c
  where c.tube_id = v.tube_id
    and c.active = true
);

create or replace function new_axe_net.deactivate_tube_comment_admin(
  p_comment_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count integer;
begin
  if not new_axe_net.is_admin() then
    raise exception '관리자 권한이 필요합니다.'
      using errcode = '42501';
  end if;

  update new_axe_net.tube_comments
  set
    active = false,
    updated_at = now()
  where id = p_comment_id
    and active = true;

  get diagnostics v_count = row_count;
  return v_count > 0;
end;
$$;

revoke all
on function new_axe_net.deactivate_tube_comment_admin(bigint)
from public, anon;

grant execute
on function new_axe_net.deactivate_tube_comment_admin(bigint)
to authenticated;

notify pgrst, 'reload schema';

select
  count(*) as comments,
  count(*) filter (where active) as active_comments,
  count(distinct tube_id) filter (where active) as videos_with_comments
from new_axe_net.tube_comments;
