-- NEW AXE NET v1.37.0
-- 040_fund_live_bridge.sql
-- FUND LIVE BRIDGE & CATCH-UP 기반
-- 전제: 001 ~ 020 공금 마이그레이션 적용 완료
--
-- 목적
-- 1) 기존 AXE NET에서 운영 중 발생한 공금 변경분을 NEW AXE NET으로 안전하게 흡수할 수 있게 한다.
-- 2) BOT(service_role)이 공금 원본/상태 RPC를 읽고 bridge audit를 기록할 수 있게 한다.
-- 3) new_axe_net 공금 변경을 Supabase Realtime으로 AXE BOT이 직접 감지할 수 있게 한다.
-- 4) 충돌은 덮어쓰지 않고 fund_bridge_conflicts에 남긴다.
--
-- 이 SQL만으로 기존 데이터를 덮어쓰지 않습니다.
-- 실제 Catch-up은 AXE BOT FUND LIVE BRIDGE가 legacy 데이터를 비교한 뒤 누락/legacy-owned 행만 반영합니다.

create table if not exists new_axe_net.fund_bridge_conflicts (
  id bigint generated by default as identity primary key,
  conflict_key text not null unique,
  entity_type text not null,
  legacy_key text,
  member_key text,
  reason text not null,
  legacy_payload jsonb not null default '{}'::jsonb,
  new_payload jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolution_note text
);

create index if not exists fund_bridge_conflicts_open_idx
  on new_axe_net.fund_bridge_conflicts(resolved_at, entity_type, last_seen_at desc);

create table if not exists new_axe_net.fund_bridge_runs (
  id bigint generated by default as identity primary key,
  mode text not null default 'shadow',
  reason text,
  started_at timestamptz not null,
  finished_at timestamptz not null default now(),
  legacy_status_rows integer not null default 0,
  legacy_request_rows integer not null default 0,
  legacy_ledger_rows integer not null default 0,
  inserted_rows integer not null default 0,
  updated_rows integer not null default 0,
  unchanged_rows integer not null default 0,
  conflict_rows integer not null default 0,
  matrix_mismatches integer not null default 0,
  summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists fund_bridge_runs_finished_idx
  on new_axe_net.fund_bridge_runs(finished_at desc);

alter table new_axe_net.fund_bridge_conflicts enable row level security;
alter table new_axe_net.fund_bridge_runs enable row level security;

revoke all on table new_axe_net.fund_bridge_conflicts from public, anon, authenticated;
revoke all on table new_axe_net.fund_bridge_runs from public, anon, authenticated;

-- 관리자 화면/SQL 점검용 읽기만 허용. 브라우저 직접 쓰기는 금지합니다.
grant select on table new_axe_net.fund_bridge_conflicts to authenticated;
grant select on table new_axe_net.fund_bridge_runs to authenticated;

drop policy if exists fund_bridge_conflicts_admin_read
  on new_axe_net.fund_bridge_conflicts;
create policy fund_bridge_conflicts_admin_read
  on new_axe_net.fund_bridge_conflicts
  for select to authenticated
  using (new_axe_net.is_admin());

drop policy if exists fund_bridge_runs_admin_read
  on new_axe_net.fund_bridge_runs;
create policy fund_bridge_runs_admin_read
  on new_axe_net.fund_bridge_runs
  for select to authenticated
  using (new_axe_net.is_admin());

-- BOT은 service_role로만 bridge 작업을 수행합니다.
grant usage on schema new_axe_net to service_role;

grant select, insert, update on table new_axe_net.fund_bridge_conflicts to service_role;
grant select, insert on table new_axe_net.fund_bridge_runs to service_role;
grant usage, select on sequence new_axe_net.fund_bridge_conflicts_id_seq to service_role;
grant usage, select on sequence new_axe_net.fund_bridge_runs_id_seq to service_role;

-- Catch-up 대상 및 비교 대상. service_role 외 브라우저 권한은 기존 정책을 유지합니다.
grant select, insert, update on table new_axe_net.fund_requests to service_role;
grant select, insert, update on table new_axe_net.fund_ledger to service_role;
grant select, insert, update on table new_axe_net.fund_exemptions to service_role;
grant select, insert, update on table new_axe_net.fund_fee_rules to service_role;
grant select, insert, update on table new_axe_net.fund_member_settings to service_role;
grant select on table new_axe_net.members to service_role;

grant usage, select on sequence new_axe_net.fund_requests_id_seq to service_role;
grant usage, select on sequence new_axe_net.fund_ledger_id_seq to service_role;
grant usage, select on sequence new_axe_net.fund_exemptions_id_seq to service_role;
grant usage, select on sequence new_axe_net.fund_fee_rules_id_seq to service_role;

-- BOT 조회 RPC 권한 보정. 이미 grant 되어 있어도 재실행 안전합니다.
grant execute on function new_axe_net.get_fund_summary(integer, integer, integer) to service_role;
grant execute on function new_axe_net.get_fund_periods() to service_role;
grant execute on function new_axe_net.get_fund_month_overview(integer, integer) to service_role;
grant execute on function new_axe_net.get_fund_month_matrix(integer, integer) to service_role;

-- get_fund_period_status는 설치 버전에 따라 존재 여부가 다를 수 있어 조건부 grant.
do $$
begin
  if to_regprocedure('new_axe_net.get_fund_period_status(integer,integer,integer)') is not null then
    execute 'grant execute on function new_axe_net.get_fund_period_status(integer, integer, integer) to service_role';
  end if;
  if to_regprocedure('new_axe_net.get_my_fund_profile(text,text)') is not null then
    execute 'grant execute on function new_axe_net.get_my_fund_profile(text, text) to service_role';
  end if;
end
$$;

-- Realtime publication에 공금 원본 테이블을 등록합니다.
-- 이미 등록된 테이블은 건너뜁니다.
do $$
declare
  v_table text;
begin
  foreach v_table in array array[
    'fund_requests',
    'fund_ledger',
    'fund_exemptions',
    'fund_fee_rules',
    'fund_member_settings',
    'members'
  ]
  loop
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'new_axe_net'
        and tablename = v_table
    ) then
      execute format(
        'alter publication supabase_realtime add table new_axe_net.%I',
        v_table
      );
    end if;
  end loop;
end
$$;

notify pgrst, 'reload schema';

-- 적용 확인
select
  (select count(*) from new_axe_net.fund_bridge_conflicts where resolved_at is null) as open_conflicts,
  (select count(*) from new_axe_net.fund_bridge_runs) as bridge_runs,
  (select count(*) from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'new_axe_net' and tablename in ('fund_requests','fund_ledger','fund_exemptions','fund_fee_rules','fund_member_settings','members')) as realtime_tables;
