-- NEW AXE NET v1.38.0
-- 041_fund_final_cutover.sql
-- CURRENT AXE NET -> NEW AXE NET 공금 최종 전환
--
-- 핵심 원칙
-- 1) 기존 AXE NET의 '현재 운영 스냅샷'을 단 한 번 정답으로 가져옵니다.
-- 2) NEW 공금 영역은 같은 트랜잭션 안에서 백업 후 통째로 교체합니다.
-- 3) 입력 잔액과 적용 후 잔액이 1원이라도 다르면 예외를 발생시켜 전체 롤백합니다.
-- 4) 최종 전환 후 Discord BOT 제출/검수는 NEW Supabase에 직접 기록합니다.
-- 5) 함수 실행 권한은 service_role에만 부여합니다.

-- =========================================================
-- 1. 최종 전환 백업
-- =========================================================
create table if not exists new_axe_net.fund_cutover_archives (
  id bigint generated by default as identity primary key,
  source text not null default 'current_axe_net',
  expected_public_balance bigint not null,
  previous_public_balance bigint not null default 0,
  previous_state jsonb not null default '{}'::jsonb,
  source_snapshot jsonb not null default '{}'::jsonb,
  source_digest text,
  created_at timestamptz not null default now()
);

create index if not exists fund_cutover_archives_created_idx
  on new_axe_net.fund_cutover_archives(created_at desc);

alter table new_axe_net.fund_cutover_archives enable row level security;
revoke all on table new_axe_net.fund_cutover_archives from public, anon, authenticated;
grant select, insert on table new_axe_net.fund_cutover_archives to service_role;
grant usage, select on sequence new_axe_net.fund_cutover_archives_id_seq to service_role;

-- 관리자 웹은 백업 내용을 직접 수정하지 못하고 조회만 허용합니다.
grant select on table new_axe_net.fund_cutover_archives to authenticated;
drop policy if exists fund_cutover_archives_admin_read on new_axe_net.fund_cutover_archives;
create policy fund_cutover_archives_admin_read
on new_axe_net.fund_cutover_archives
for select to authenticated
using (new_axe_net.is_admin());


-- =========================================================
-- 1-B. 공금 런타임 원본 상태 (동기화 기능이 아닌 단일 전환 플래그)
-- =========================================================
create table if not exists new_axe_net.fund_runtime_config (
  id integer primary key check (id = 1),
  primary_source text not null default 'legacy' check (primary_source in ('legacy','new_axe_net')),
  cutover_at timestamptz,
  cutover_backup_id bigint references new_axe_net.fund_cutover_archives(id) on delete set null,
  updated_at timestamptz not null default now()
);

insert into new_axe_net.fund_runtime_config (id, primary_source)
values (1, 'legacy')
on conflict (id) do nothing;

alter table new_axe_net.fund_runtime_config enable row level security;
revoke all on table new_axe_net.fund_runtime_config from public, anon, authenticated;
grant select, insert, update on table new_axe_net.fund_runtime_config to service_role;
grant select on table new_axe_net.fund_runtime_config to authenticated;
drop policy if exists fund_runtime_config_admin_read on new_axe_net.fund_runtime_config;
create policy fund_runtime_config_admin_read
on new_axe_net.fund_runtime_config
for select to authenticated
using (new_axe_net.is_admin());

-- =========================================================
-- 2. CURRENT AXE NET 스냅샷을 원자적으로 적용
-- =========================================================
create or replace function new_axe_net.apply_current_axe_fund_snapshot(
  p_payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_expected bigint;
  v_incoming bigint := 0;
  v_previous bigint := 0;
  v_final bigint := 0;
  v_backup_id bigint;
  v_previous_state jsonb;
  v_row jsonb;
  v_request_id bigint;
  v_request_map jsonb := '{}'::jsonb;
  v_source_ref text;
  v_member_key text;
  v_missing text;
  v_count_members integer := 0;
  v_count_requests integer := 0;
  v_count_ledger integer := 0;
  v_count_exemptions integer := 0;
  v_count_fees integer := 0;
  v_now timestamptz := now();
begin
  perform pg_advisory_xact_lock(1380138061);

  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception '공금 최종 전환 payload가 올바르지 않습니다.' using errcode = '22023';
  end if;

  if jsonb_typeof(coalesce(p_payload->'members', 'null'::jsonb)) <> 'array'
     or jsonb_typeof(coalesce(p_payload->'requests', 'null'::jsonb)) <> 'array'
     or jsonb_typeof(coalesce(p_payload->'ledger', 'null'::jsonb)) <> 'array'
     or jsonb_typeof(coalesce(p_payload->'exemptions', 'null'::jsonb)) <> 'array'
     or jsonb_typeof(coalesce(p_payload->'fee_rules', 'null'::jsonb)) <> 'array' then
    raise exception 'members/requests/ledger/exemptions/fee_rules 배열이 모두 필요합니다.' using errcode = '22023';
  end if;

  if exists (
    select 1 from new_axe_net.fund_runtime_config c
    where c.id = 1 and c.primary_source = 'new_axe_net'
  ) then
    raise exception '공금은 이미 NEW AXE NET으로 최종 전환되었습니다.' using errcode = '22023';
  end if;

  v_expected := nullif(p_payload->>'expected_public_balance', '')::bigint;
  if v_expected is null then
    raise exception '현재 AXE NET 기준 잔액이 없습니다.' using errcode = '22023';
  end if;

  -- BOT이 정규화한 incoming 원장 자체로 한 번 더 잔액 검증.
  select coalesce(sum(
    case coalesce(x->>'direction', '수입')
      when '지출' then -coalesce(nullif(x->>'public_amount','')::bigint, 0)
      when '조정' then  coalesce(nullif(x->>'public_amount','')::bigint, 0)
      else              coalesce(nullif(x->>'public_amount','')::bigint, 0)
    end
  ), 0)
  into v_incoming
  from jsonb_array_elements(p_payload->'ledger') x
  where coalesce(x->>'status', 'active') = 'active';

  if v_incoming <> v_expected then
    raise exception '전환 입력 원장 잔액(%)과 현재 AXE NET 잔액(%)이 다릅니다.', v_incoming, v_expected
      using errcode = '22023';
  end if;

  -- source_ref 중복은 request_id 연결을 모호하게 만들므로 사전 차단.
  if exists (
    select 1
    from (
      select nullif(btrim(x->>'source_ref'), '') as source_ref, count(*) as c
      from jsonb_array_elements(p_payload->'requests') x
      group by nullif(btrim(x->>'source_ref'), '')
      having nullif(btrim(x->>'source_ref'), '') is not null and count(*) > 1
    ) q
  ) then
    raise exception '공금 신청 source_ref가 중복되었습니다.' using errcode = '23505';
  end if;

  -- 동일 멤버/주차 active payment 중복은 NEW의 회계 제약과 충돌하므로 사전 차단.
  if exists (
    select 1
    from (
      select
        x->>'member_key' as member_key,
        nullif(x->>'year','')::integer as year,
        nullif(x->>'month','')::integer as month,
        nullif(x->>'week','')::integer as week,
        count(*) as c
      from jsonb_array_elements(p_payload->'ledger') x
      where coalesce(x->>'status','active') = 'active'
        and x->>'entry_type' = 'payment'
        and nullif(x->>'member_key','') is not null
      group by 1,2,3,4
      having count(*) > 1
    ) q
  ) then
    raise exception '같은 멤버/주차에 활성 납부 원장이 2건 이상 있습니다.' using errcode = '23505';
  end if;

  -- payload에 들어간 모든 member_key가 NEW members에 존재하는지 검증.
  with incoming_keys as (
    select distinct nullif(btrim(k), '') as member_key
    from (
      select x->>'member_key' k from jsonb_array_elements(p_payload->'members') x
      union all
      select x->>'member_key' k from jsonb_array_elements(p_payload->'requests') x
      union all
      select x->>'member_key' k from jsonb_array_elements(p_payload->'ledger') x
      union all
      select x->>'member_key' k from jsonb_array_elements(p_payload->'exemptions') x
    ) s
    where nullif(btrim(k), '') is not null
  )
  select string_agg(i.member_key, ', ' order by i.member_key)
  into v_missing
  from incoming_keys i
  left join new_axe_net.members m on m.member_key = i.member_key
  where m.member_key is null;

  if v_missing is not null then
    raise exception 'NEW AXE NET에서 찾을 수 없는 멤버가 있습니다: %', v_missing using errcode = '22023';
  end if;

  select coalesce(sum(
    case l.direction
      when '지출' then -l.public_amount
      when '조정' then  l.public_amount
      else              l.public_amount
    end
  ), 0)
  into v_previous
  from new_axe_net.fund_ledger l
  where l.status = 'active';

  select jsonb_build_object(
    'fund_ledger', coalesce((select jsonb_agg(to_jsonb(l) order by l.id) from new_axe_net.fund_ledger l), '[]'::jsonb),
    'fund_requests', coalesce((select jsonb_agg(to_jsonb(r) order by r.id) from new_axe_net.fund_requests r), '[]'::jsonb),
    'fund_exemptions', coalesce((select jsonb_agg(to_jsonb(e) order by e.id) from new_axe_net.fund_exemptions e), '[]'::jsonb),
    'fund_fee_rules', coalesce((select jsonb_agg(to_jsonb(f) order by f.id) from new_axe_net.fund_fee_rules f), '[]'::jsonb),
    'fund_member_settings', coalesce((select jsonb_agg(to_jsonb(s) order by s.member_key) from new_axe_net.fund_member_settings s), '[]'::jsonb),
    'fund_status_snapshot', coalesce((select jsonb_agg(to_jsonb(s) order by s.id) from new_axe_net.fund_status_snapshot s), '[]'::jsonb)
  ) into v_previous_state;

  insert into new_axe_net.fund_cutover_archives (
    source,
    expected_public_balance,
    previous_public_balance,
    previous_state,
    source_snapshot,
    source_digest
  ) values (
    coalesce(nullif(btrim(p_payload->>'source'), ''), 'current_axe_net'),
    v_expected,
    v_previous,
    v_previous_state,
    p_payload,
    nullif(btrim(p_payload->>'source_digest'), '')
  ) returning id into v_backup_id;

  -- 여기부터 같은 DB transaction. 뒤에서 잔액 검증이 실패하면 전부 원복됩니다.
  delete from new_axe_net.fund_ledger where true;
  delete from new_axe_net.fund_requests where true;
  delete from new_axe_net.fund_exemptions where true;
  delete from new_axe_net.fund_fee_rules where true;
  delete from new_axe_net.fund_status_snapshot where true;

  update new_axe_net.fund_member_settings
  set enabled = false,
      note = case when note is null then 'Final cutover: current AXE NET 비대상' else note end,
      updated_by = 'AXE BOT FINAL CUTOVER',
      updated_at = v_now
  where true;

  -- 공금 대상 멤버
  for v_row in select value from jsonb_array_elements(p_payload->'members') loop
    v_member_key := nullif(btrim(v_row->>'member_key'), '');
    if v_member_key is null then continue; end if;

    insert into new_axe_net.fund_member_settings (
      member_key, enabled, join_date_override, note, updated_by, created_at, updated_at
    ) values (
      v_member_key,
      coalesce((v_row->>'enabled')::boolean, true),
      nullif(v_row->>'join_date_override','')::date,
      nullif(v_row->>'note',''),
      'AXE BOT FINAL CUTOVER',
      v_now,
      v_now
    )
    on conflict (member_key) do update set
      enabled = excluded.enabled,
      join_date_override = excluded.join_date_override,
      note = excluded.note,
      updated_by = excluded.updated_by,
      updated_at = excluded.updated_at;
    v_count_members := v_count_members + 1;
  end loop;

  -- 요율
  for v_row in select value from jsonb_array_elements(p_payload->'fee_rules') loop
    insert into new_axe_net.fund_fee_rules (
      legacy_id, source_id, start_year, start_month, start_week,
      weekly_fee, note, enabled, source_key, created_at, updated_at
    ) values (
      null,
      nullif(v_row->>'source_id',''),
      (v_row->>'start_year')::integer,
      (v_row->>'start_month')::integer,
      (v_row->>'start_week')::integer,
      (v_row->>'weekly_fee')::integer,
      nullif(v_row->>'note',''),
      coalesce((v_row->>'enabled')::boolean, true),
      v_row->>'source_key',
      coalesce(nullif(v_row->>'created_at','')::timestamptz, v_now),
      coalesce(nullif(v_row->>'updated_at','')::timestamptz, v_now)
    );
    v_count_fees := v_count_fees + 1;
  end loop;

  -- 면제는 NEW 엔진이 사용하는 주차별 행으로 입력
  for v_row in select value from jsonb_array_elements(p_payload->'exemptions') loop
    insert into new_axe_net.fund_exemptions (
      legacy_id, member_key, nickname, year, month, week,
      exemption_type, reason, enabled, source_key, created_by,
      created_at, updated_at, range_key
    ) values (
      null,
      v_row->>'member_key',
      nullif(v_row->>'nickname',''),
      (v_row->>'year')::integer,
      (v_row->>'month')::integer,
      (v_row->>'week')::integer,
      coalesce(nullif(v_row->>'exemption_type',''), 'final_cutover'),
      nullif(v_row->>'reason',''),
      coalesce((v_row->>'enabled')::boolean, true),
      v_row->>'source_key',
      coalesce(nullif(v_row->>'created_by',''), 'AXE BOT FINAL CUTOVER'),
      coalesce(nullif(v_row->>'created_at','')::timestamptz, v_now),
      coalesce(nullif(v_row->>'updated_at','')::timestamptz, v_now),
      nullif(v_row->>'range_key','')
    );
    v_count_exemptions := v_count_exemptions + 1;
  end loop;

  -- 신청: source_ref -> 새 request id 매핑을 함수 내부에서 유지
  for v_row in select value from jsonb_array_elements(p_payload->'requests') loop
    v_source_ref := nullif(btrim(v_row->>'source_ref'), '');
    insert into new_axe_net.fund_requests (
      legacy_id, guild_id, discord_user_id, discord_name,
      member_key, nickname, year, month, week, amount, status,
      evidence_url, memo, reviewer_discord_name, reviewed_at,
      source_key, payment_mode, public_amount, company_amount,
      client_request_id, sheet_request_id, created_at, updated_at,
      review_note, submitted_via, submitted_by_name, proxy_admin_name
    ) values (
      null,
      nullif(v_row->>'guild_id',''),
      nullif(v_row->>'discord_user_id',''),
      nullif(v_row->>'discord_name',''),
      v_row->>'member_key',
      nullif(v_row->>'nickname',''),
      (v_row->>'year')::integer,
      (v_row->>'month')::integer,
      (v_row->>'week')::integer,
      (v_row->>'amount')::integer,
      v_row->>'status',
      nullif(v_row->>'evidence_url',''),
      nullif(v_row->>'memo',''),
      nullif(v_row->>'reviewer_discord_name',''),
      nullif(v_row->>'reviewed_at','')::timestamptz,
      v_row->>'source_key',
      nullif(v_row->>'payment_mode',''),
      coalesce(nullif(v_row->>'public_amount','')::integer, 0),
      coalesce(nullif(v_row->>'company_amount','')::integer, 0),
      nullif(v_row->>'client_request_id',''),
      nullif(v_row->>'sheet_request_id',''),
      coalesce(nullif(v_row->>'created_at','')::timestamptz, v_now),
      coalesce(nullif(v_row->>'updated_at','')::timestamptz, v_now),
      nullif(v_row->>'review_note',''),
      coalesce(nullif(v_row->>'submitted_via',''), 'final_cutover'),
      nullif(v_row->>'submitted_by_name',''),
      nullif(v_row->>'proxy_admin_name','')
    ) returning id into v_request_id;

    if v_source_ref is not null then
      v_request_map := v_request_map || jsonb_build_object(v_source_ref, v_request_id);
    end if;
    v_count_requests := v_count_requests + 1;
  end loop;

  -- 실제 원장
  for v_row in select value from jsonb_array_elements(p_payload->'ledger') loop
    v_source_ref := nullif(btrim(v_row->>'request_source_ref'), '');
    v_request_id := case
      when v_source_ref is not null and (v_request_map ? v_source_ref)
        then (v_request_map->>v_source_ref)::bigint
      else null
    end;

    insert into new_axe_net.fund_ledger (
      legacy_id, member_key, nickname, year, month, week,
      entry_type, amount, public_amount, company_amount, status,
      approved_by_name, approved_at, legacy_request_key, source_key,
      memo, created_at, updated_at, ledger_date, ledger_type,
      category, direction, account, evidence_url, evidence_file_id,
      operation_key, request_id, deleted_at, deleted_by, delete_reason
    ) values (
      null,
      nullif(v_row->>'member_key',''),
      nullif(v_row->>'nickname',''),
      nullif(v_row->>'year','')::integer,
      nullif(v_row->>'month','')::integer,
      nullif(v_row->>'week','')::integer,
      v_row->>'entry_type',
      (v_row->>'amount')::integer,
      coalesce(nullif(v_row->>'public_amount','')::integer, 0),
      coalesce(nullif(v_row->>'company_amount','')::integer, 0),
      coalesce(nullif(v_row->>'status',''), 'active'),
      nullif(v_row->>'approved_by_name',''),
      nullif(v_row->>'approved_at','')::timestamptz,
      nullif(v_row->>'legacy_request_key',''),
      v_row->>'source_key',
      nullif(v_row->>'memo',''),
      coalesce(nullif(v_row->>'created_at','')::timestamptz, v_now),
      coalesce(nullif(v_row->>'updated_at','')::timestamptz, v_now),
      coalesce(nullif(v_row->>'ledger_date','')::timestamptz, v_now),
      coalesce(nullif(v_row->>'ledger_type',''), '직접기입'),
      nullif(v_row->>'category',''),
      v_row->>'direction',
      v_row->>'account',
      nullif(v_row->>'evidence_url',''),
      nullif(v_row->>'evidence_file_id',''),
      nullif(v_row->>'operation_key',''),
      v_request_id,
      nullif(v_row->>'deleted_at','')::timestamptz,
      nullif(v_row->>'deleted_by',''),
      nullif(v_row->>'delete_reason','')
    );
    v_count_ledger := v_count_ledger + 1;
  end loop;

  -- 과거 Live Bridge 충돌은 최종 전환으로 종료 표시. 기록 자체는 보존합니다.
  update new_axe_net.fund_bridge_conflicts
  set resolved_at = coalesce(resolved_at, v_now),
      resolution_note = coalesce(resolution_note, 'CURRENT AXE NET final cutover v1.38.0')
  where resolved_at is null;

  select coalesce(sum(
    case l.direction
      when '지출' then -l.public_amount
      when '조정' then  l.public_amount
      else              l.public_amount
    end
  ), 0)
  into v_final
  from new_axe_net.fund_ledger l
  where l.status = 'active';

  if v_final <> v_expected then
    raise exception '최종 적용 후 NEW 잔액(%)과 현재 AXE NET 잔액(%)이 다릅니다. 전체 작업을 롤백합니다.', v_final, v_expected
      using errcode = '22023';
  end if;

  -- 이 플래그 역시 같은 transaction 안에서만 NEW로 바뀝니다.
  insert into new_axe_net.fund_runtime_config (id, primary_source, cutover_at, cutover_backup_id, updated_at)
  values (1, 'new_axe_net', v_now, v_backup_id, v_now)
  on conflict (id) do update set
    primary_source = excluded.primary_source,
    cutover_at = excluded.cutover_at,
    cutover_backup_id = excluded.cutover_backup_id,
    updated_at = excluded.updated_at;

  return jsonb_build_object(
    'success', true,
    'backup_id', v_backup_id,
    'expected_public_balance', v_expected,
    'previous_public_balance', v_previous,
    'final_public_balance', v_final,
    'counts', jsonb_build_object(
      'members', v_count_members,
      'requests', v_count_requests,
      'ledger', v_count_ledger,
      'exemptions', v_count_exemptions,
      'fee_rules', v_count_fees
    ),
    'cutover_at', v_now
  );
end;
$$;

revoke all on function new_axe_net.apply_current_axe_fund_snapshot(jsonb)
from public, anon, authenticated;
grant execute on function new_axe_net.apply_current_axe_fund_snapshot(jsonb)
to service_role;

-- =========================================================
-- 3. AXE BOT -> NEW Supabase 직접 제출
-- =========================================================
create or replace function new_axe_net.bot_submit_fund_request(
  p_member_key text,
  p_discord_user_id text,
  p_discord_name text,
  p_year integer,
  p_month integer,
  p_week integer,
  p_amount integer,
  p_payment_mode text,
  p_public_amount integer,
  p_company_amount integer,
  p_evidence_url text,
  p_memo text default null,
  p_client_request_id text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_member new_axe_net.members%rowtype;
  v_id bigint;
  v_existing bigint;
  v_period_end date;
  v_period_start date;
  v_join date;
  v_today date := (now() at time zone 'Asia/Seoul')::date;
  v_amount integer;
  v_public integer;
  v_company integer;
  v_source_key text;
begin
  perform pg_advisory_xact_lock(1380138062);

  if not exists (
    select 1 from new_axe_net.fund_runtime_config c
    where c.id = 1 and c.primary_source = 'new_axe_net'
  ) then
    raise exception '공금 최종 전환 전에는 NEW 제출을 사용할 수 없습니다.' using errcode = '55000';
  end if;

  if nullif(btrim(p_member_key),'') is null then
    raise exception '멤버 정보가 없습니다.' using errcode = '22023';
  end if;

  select m.* into v_member
  from new_axe_net.members m
  left join new_axe_net.fund_member_settings s on s.member_key = m.member_key
  where m.member_key = p_member_key
    and m.status = 'active'
    and coalesce(s.enabled, true) = true
  limit 1;

  if not found then
    raise exception '현재 공금 대상 멤버를 찾을 수 없습니다.' using errcode = '22023';
  end if;

  if nullif(btrim(p_discord_user_id),'') is null
     or nullif(btrim(v_member.discord_user_id),'') is null
     or btrim(v_member.discord_user_id) <> btrim(p_discord_user_id) then
    raise exception 'Discord 계정과 NEW AXE NET 멤버 연결이 일치하지 않습니다.' using errcode = '42501';
  end if;

  select coalesce(s.join_date_override, v_member.joined_date)
  into v_join
  from new_axe_net.fund_member_settings s
  where s.member_key = p_member_key;
  v_join := coalesce(v_join, v_member.joined_date);

  v_period_end := new_axe_net.fund_period_end(p_year, p_month, p_week);
  if v_period_end is null then
    raise exception '존재하지 않는 공금 주차입니다.' using errcode = '22023';
  end if;
  v_period_start := v_period_end - 6;
  if v_period_start > v_today then
    raise exception '아직 시작하지 않은 주차에는 신청할 수 없습니다.' using errcode = '22023';
  end if;
  if v_join is not null and v_join > v_period_end then
    raise exception '가입 전 주차에는 신청할 수 없습니다.' using errcode = '22023';
  end if;

  if p_payment_mode not in ('공용계좌','회사잔고','분할납부') then
    raise exception '올바르지 않은 납부 방식입니다.' using errcode = '22023';
  end if;

  v_amount := coalesce(p_amount, new_axe_net.fund_weekly_fee(p_year,p_month,p_week));
  v_public := coalesce(p_public_amount, 0);
  v_company := coalesce(p_company_amount, 0);
  if v_amount <= 0 then raise exception '납부 금액은 0원보다 커야 합니다.' using errcode = '22023'; end if;

  if p_payment_mode = '공용계좌' then
    v_public := v_amount; v_company := 0;
  elsif p_payment_mode = '회사잔고' then
    v_public := 0; v_company := v_amount;
  else
    if v_public <= 0 or v_company <= 0 or v_public + v_company <> v_amount then
      raise exception '분할납부 금액 구성이 올바르지 않습니다.' using errcode = '22023';
    end if;
  end if;

  if nullif(btrim(p_evidence_url),'') is null then
    raise exception '증빙 스크린샷이 필요합니다.' using errcode = '22023';
  end if;

  if exists (
    select 1 from new_axe_net.fund_exemptions e
    where e.member_key=p_member_key and e.year=p_year and e.month=p_month and e.week=p_week and e.enabled=true
  ) then
    raise exception '해당 주차는 면제 처리되어 있습니다.' using errcode = '22023';
  end if;

  if exists (
    select 1 from new_axe_net.fund_ledger l
    where l.member_key=p_member_key and l.year=p_year and l.month=p_month and l.week=p_week
      and l.entry_type='payment' and l.status='active'
  ) then
    raise exception '이미 해당 주차의 납부가 완료되었습니다.' using errcode = '23505';
  end if;

  if nullif(btrim(p_client_request_id),'') is not null then
    select r.id into v_existing
    from new_axe_net.fund_requests r
    where r.client_request_id = btrim(p_client_request_id)
    order by r.id desc limit 1;
    if v_existing is not null then
      return jsonb_build_object('success',true,'id',v_existing,'idempotent',true);
    end if;
  end if;

  if exists (
    select 1 from new_axe_net.fund_requests r
    where r.member_key=p_member_key and r.year=p_year and r.month=p_month and r.week=p_week
      and r.status in ('pending','hold')
  ) then
    raise exception '이미 검수대기 또는 보류 중인 신청이 있습니다.' using errcode = '23505';
  end if;

  v_source_key := 'discord_bot:' || coalesce(nullif(btrim(p_client_request_id),''), new_axe_net.new_fund_operation_key('request'));

  insert into new_axe_net.fund_requests (
    legacy_id, guild_id, discord_user_id, discord_name, member_key, nickname,
    year, month, week, amount, status, evidence_url, memo,
    source_key, payment_mode, public_amount, company_amount,
    client_request_id, submitted_via, submitted_by_name
  ) values (
    null, null, nullif(btrim(p_discord_user_id),''), nullif(btrim(p_discord_name),''),
    v_member.member_key, v_member.nickname,
    p_year,p_month,p_week,v_amount,'pending',btrim(p_evidence_url),nullif(btrim(p_memo),''),
    v_source_key,p_payment_mode,v_public,v_company,
    nullif(btrim(p_client_request_id),''),'discord_bot',v_member.nickname
  ) returning id into v_id;

  return jsonb_build_object(
    'success',true,
    'id',v_id,
    'nickname',v_member.nickname,
    'member_key',v_member.member_key,
    'year',p_year,'month',p_month,'week',p_week,
    'amount',v_amount,
    'payment_mode',p_payment_mode,
    'public_amount',v_public,
    'company_amount',v_company,
    'evidence_url',btrim(p_evidence_url),
    'status','pending'
  );
end;
$$;

revoke all on function new_axe_net.bot_submit_fund_request(
  text,text,text,integer,integer,integer,integer,text,integer,integer,text,text,text
) from public, anon, authenticated;
grant execute on function new_axe_net.bot_submit_fund_request(
  text,text,text,integer,integer,integer,integer,text,integer,integer,text,text,text
) to service_role;

-- =========================================================
-- 4. AXE BOT -> NEW Supabase 직접 승인/반려
-- =========================================================
create or replace function new_axe_net.bot_review_fund_request(
  p_request_id bigint,
  p_action text,
  p_reviewer_name text,
  p_review_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_request new_axe_net.fund_requests%rowtype;
  v_action text := lower(btrim(coalesce(p_action,'')));
  v_ledger_id bigint;
  v_operation_key text;
  v_reviewer text := coalesce(nullif(btrim(p_reviewer_name),''),'AXE BOT');
begin
  perform pg_advisory_xact_lock(1380138063);

  if not exists (
    select 1 from new_axe_net.fund_runtime_config c
    where c.id = 1 and c.primary_source = 'new_axe_net'
  ) then
    raise exception '공금 최종 전환 전에는 NEW 검수를 사용할 수 없습니다.' using errcode = '55000';
  end if;

  select * into v_request
  from new_axe_net.fund_requests
  where id = p_request_id
  for update;

  if not found then raise exception '신청을 찾을 수 없습니다.' using errcode = '22023'; end if;

  if v_action in ('approve','approved','승인') then
    if v_request.status = 'approved' then
      select l.id into v_ledger_id from new_axe_net.fund_ledger l
      where l.request_id=p_request_id and l.status='active' order by l.id desc limit 1;
      return jsonb_build_object('success',true,'idempotent',true,'status','approved','ledger_id',v_ledger_id);
    end if;
    if v_request.status not in ('pending','hold') then
      raise exception '이미 처리된 신청입니다.' using errcode = '22023';
    end if;
    if exists (
      select 1 from new_axe_net.fund_ledger l
      where l.member_key=v_request.member_key and l.year=v_request.year and l.month=v_request.month and l.week=v_request.week
        and l.entry_type='payment' and l.status='active'
    ) then
      raise exception '이미 해당 주차에 활성 납부 기록이 있습니다.' using errcode = '23505';
    end if;

    v_operation_key := new_axe_net.new_fund_operation_key('discord_bot_approved');
    insert into new_axe_net.fund_ledger (
      legacy_id, member_key, nickname, year, month, week,
      entry_type, amount, public_amount, company_amount, status,
      approved_by_name, approved_at, legacy_request_key, source_key,
      memo, ledger_date, ledger_type, category, direction, account,
      evidence_url, operation_key, request_id
    ) values (
      null,v_request.member_key,v_request.nickname,v_request.year,v_request.month,v_request.week,
      'payment',v_request.amount,v_request.public_amount,v_request.company_amount,'active',
      v_reviewer,now(),'new_request:'||v_request.id::text,v_operation_key,
      concat_ws(' · ', nullif(v_request.memo,''), nullif(p_review_note,'')),
      now(),'공금납부','주간공금','수입',coalesce(v_request.payment_mode,'공용계좌'),
      v_request.evidence_url,v_operation_key,v_request.id
    ) returning id into v_ledger_id;

    update new_axe_net.fund_requests set
      status='approved', reviewer_discord_name=v_reviewer, reviewed_at=now(),
      review_note=nullif(btrim(p_review_note),'')
    where id=p_request_id;

    return jsonb_build_object('success',true,'status','approved','ledger_id',v_ledger_id);
  elsif v_action in ('reject','rejected','반려','거절') then
    if v_request.status = 'rejected' then
      return jsonb_build_object('success',true,'idempotent',true,'status','rejected');
    end if;
    if v_request.status not in ('pending','hold') then
      raise exception '이미 처리된 신청입니다.' using errcode = '22023';
    end if;
    update new_axe_net.fund_requests set
      status='rejected', reviewer_discord_name=v_reviewer, reviewed_at=now(),
      review_note=nullif(btrim(p_review_note),'')
    where id=p_request_id;
    return jsonb_build_object('success',true,'status','rejected');
  else
    raise exception 'action은 승인 또는 반려여야 합니다.' using errcode = '22023';
  end if;
end;
$$;

revoke all on function new_axe_net.bot_review_fund_request(bigint,text,text,text)
from public, anon, authenticated;
grant execute on function new_axe_net.bot_review_fund_request(bigint,text,text,text)
to service_role;

-- BOT 조회/Storage 권한 보정
grant usage on schema new_axe_net to service_role;
grant select, insert, update, delete on table new_axe_net.fund_requests to service_role;
grant select, insert, update, delete on table new_axe_net.fund_ledger to service_role;
grant select, insert, update, delete on table new_axe_net.fund_exemptions to service_role;
grant select, insert, update, delete on table new_axe_net.fund_fee_rules to service_role;
grant select, insert, update on table new_axe_net.fund_member_settings to service_role;
grant select, delete on table new_axe_net.fund_status_snapshot to service_role;
grant select on table new_axe_net.members to service_role;
grant select, insert, update on table new_axe_net.fund_runtime_config to service_role;
grant usage, select on sequence new_axe_net.fund_requests_id_seq to service_role;
grant usage, select on sequence new_axe_net.fund_ledger_id_seq to service_role;
grant usage, select on sequence new_axe_net.fund_exemptions_id_seq to service_role;
grant usage, select on sequence new_axe_net.fund_fee_rules_id_seq to service_role;

grant execute on function new_axe_net.get_fund_summary(integer,integer,integer) to service_role;
grant execute on function new_axe_net.get_fund_month_matrix(integer,integer) to service_role;

notify pgrst, 'reload schema';

-- =========================================================
-- 적용 확인 (SQL Editor 결과용)
-- =========================================================
select
  to_regclass('new_axe_net.fund_cutover_archives') is not null as archive_ready,
  to_regclass('new_axe_net.fund_runtime_config') is not null as runtime_config_ready,
  to_regprocedure('new_axe_net.apply_current_axe_fund_snapshot(jsonb)') is not null as cutover_rpc_ready,
  to_regprocedure('new_axe_net.bot_submit_fund_request(text,text,text,integer,integer,integer,integer,text,integer,integer,text,text,text)') is not null as bot_submit_ready,
  to_regprocedure('new_axe_net.bot_review_fund_request(bigint,text,text,text)') is not null as bot_review_ready;
