-- NEW AXE NET v1.42.0
-- 044_member_shortcuts.sql
-- 사용자별 바로가기(Quick Access)
--
-- 운영 원칙
-- 1) 멤버별 최대 6개 바로가기를 Supabase에 저장합니다.
-- 2) 일반 멤버는 HttpOnly 멤버 세션을 검증하는 Vercel API를 통해 service_role로 읽기/쓰기 합니다.
-- 3) 최고관리자처럼 이메일 관리자 세션만 사용하는 경우에도 본인 member_key의 바로가기는 직접 사용할 수 있도록 RLS를 둡니다.
-- 4) 표시 이름은 사용자가 직접 정하고, 이동 대상은 NEW AXE NET 내부 허용 기능으로 제한합니다.

create table if not exists new_axe_net.member_shortcuts (
  id bigint generated by default as identity primary key,
  member_key text not null references new_axe_net.members(member_key) on delete cascade,
  label text not null,
  target_key text not null,
  sort_order smallint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint member_shortcuts_label_length_check
    check (char_length(btrim(label)) between 1 and 24),

  constraint member_shortcuts_sort_order_check
    check (sort_order between 0 and 99),

  constraint member_shortcuts_target_key_check
    check (target_key in (
      'home',
      'notice.general', 'notice.patch', 'notice.operations',
      'info.craft', 'info.quest', 'info.process', 'info.modbook', 'info.skill',
      'outlaw.stats', 'outlaw.guide', 'outlaw.map', 'tube',
      'fund.overview', 'fund.payment', 'fund.submissions',
      'fund.review', 'fund.history', 'fund.balance', 'fund.feeRules',
      'fund.exemptions', 'fund.integrity', 'fund.fundMembers',
      'assets.accounts', 'assets.company', 'assets.returns',
      'members'
    ))
);

create index if not exists member_shortcuts_member_order_idx
  on new_axe_net.member_shortcuts(member_key, sort_order, id);

alter table new_axe_net.member_shortcuts enable row level security;

-- 이메일 관리자 세션이 가리키는 실제 member_key를 안전하게 반환합니다.
create or replace function new_axe_net.current_admin_member_key()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select account.member_key
  from new_axe_net.admin_accounts account
  join new_axe_net.members member
    on member.member_key = account.member_key
  where account.user_id = auth.uid()
    and account.enabled = true
    and account.admin_level in ('superadmin', 'operator')
    and member.status = 'active'
    and lower(coalesce(member.role, '')) = 'admin'
  limit 1;
$$;

revoke all on function new_axe_net.current_admin_member_key() from public, anon;
grant execute on function new_axe_net.current_admin_member_key() to authenticated;

-- 일반 멤버는 브라우저에서 테이블을 직접 만지지 않습니다.
revoke all on table new_axe_net.member_shortcuts from public, anon, authenticated;

-- Vercel member-session API용.
grant select, insert, update, delete on table new_axe_net.member_shortcuts to service_role;
grant usage, select on sequence new_axe_net.member_shortcuts_id_seq to service_role;
grant usage on schema new_axe_net to service_role;

-- 이메일 관리자 로그인만 사용하는 최고관리자도 자신의 바로가기를 쓸 수 있게 최소 권한만 허용합니다.
grant select, insert, update, delete on table new_axe_net.member_shortcuts to authenticated;
grant usage, select on sequence new_axe_net.member_shortcuts_id_seq to authenticated;

-- 이전 실행이 있어도 정책을 안전하게 재적용합니다.
drop policy if exists member_shortcuts_admin_select on new_axe_net.member_shortcuts;
drop policy if exists member_shortcuts_admin_insert on new_axe_net.member_shortcuts;
drop policy if exists member_shortcuts_admin_update on new_axe_net.member_shortcuts;
drop policy if exists member_shortcuts_admin_delete on new_axe_net.member_shortcuts;

create policy member_shortcuts_admin_select
on new_axe_net.member_shortcuts
for select to authenticated
using (member_key = new_axe_net.current_admin_member_key());

create policy member_shortcuts_admin_insert
on new_axe_net.member_shortcuts
for insert to authenticated
with check (member_key = new_axe_net.current_admin_member_key());

create policy member_shortcuts_admin_update
on new_axe_net.member_shortcuts
for update to authenticated
using (member_key = new_axe_net.current_admin_member_key())
with check (member_key = new_axe_net.current_admin_member_key());

create policy member_shortcuts_admin_delete
on new_axe_net.member_shortcuts
for delete to authenticated
using (member_key = new_axe_net.current_admin_member_key());

notify pgrst, 'reload schema';

-- 적용 확인: 아래 항목이 모두 true이면 준비 완료입니다.
select
  to_regclass('new_axe_net.member_shortcuts') is not null as shortcuts_table_ready,
  to_regprocedure('new_axe_net.current_admin_member_key()') is not null as admin_identity_ready,
  has_table_privilege('service_role', 'new_axe_net.member_shortcuts', 'SELECT') as service_select_ready,
  has_table_privilege('service_role', 'new_axe_net.member_shortcuts', 'INSERT') as service_insert_ready,
  has_table_privilege('service_role', 'new_axe_net.member_shortcuts', 'UPDATE') as service_update_ready,
  has_table_privilege('service_role', 'new_axe_net.member_shortcuts', 'DELETE') as service_delete_ready;
