-- AXE NET v1.43.0
-- 045_axe_ai_foundation.sql
-- AXE AI · Supabase Foundation
--
-- 목적
-- 1) AXE NET 전용 AI 지식 / 별칭 / 미답변 / 질문 로그 저장소
-- 2) pgvector + pg_trgm 기반 Hybrid Search 준비
-- 3) 브라우저 일반 사용자에게는 원본 AI 테이블 비공개
-- 4) 관리자(Auth + new_axe_net.is_admin())와 service_role만 관리 가능
--
-- 중요
-- - public schema / AXE WAR 기존 데이터는 수정하지 않습니다.
-- - 실제 AI 답변 모델 호출과 embedding 생성은 다음 단계(BOT/서버)에서 연결합니다.
-- - embedding 컬럼은 OpenAI text-embedding-3-small 호환 1536차원 기준입니다.

begin;

create schema if not exists new_axe_net;

-- =========================================================
-- 0. Extensions
-- =========================================================
create extension if not exists vector with schema extensions;
create extension if not exists pg_trgm with schema extensions;

grant usage on schema new_axe_net to authenticated, service_role;

-- =========================================================
-- 1. 공통 정규화 함수
-- =========================================================
create or replace function new_axe_net.ai_normalize_text(p_value text)
returns text
language sql
immutable
set search_path = ''
as $$
  select regexp_replace(
    lower(coalesce(p_value, '')),
    '[^0-9a-z가-힣]+',
    '',
    'g'
  );
$$;

revoke all on function new_axe_net.ai_normalize_text(text) from public, anon;
grant execute on function new_axe_net.ai_normalize_text(text)
to authenticated, service_role;

-- =========================================================
-- 2. AI 지식
-- =========================================================
create table if not exists new_axe_net.ai_knowledge (
  id bigint generated by default as identity primary key,

  domain text not null default 'general',
  category text,
  title text not null,
  content text not null,

  source_type text not null default 'manual'
    check (source_type in (
      'manual',
      'info',
      'fund',
      'member',
      'asset',
      'outlaw',
      'notice',
      'rules',
      'map',
      'community',
      'legacy'
    )),
  source_table text,
  source_key text,

  priority integer not null default 0,
  active boolean not null default true,

  -- embedding 생성은 BOT/서버가 담당합니다.
  embedding extensions.vector(1536),
  embedding_model text,
  embedding_status text not null default 'pending'
    check (embedding_status in ('pending', 'ready', 'error', 'disabled')),
  embedding_error text,
  embedded_at timestamptz,

  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint ai_knowledge_title_not_blank
    check (btrim(title) <> ''),
  constraint ai_knowledge_content_not_blank
    check (btrim(content) <> '')
);

create unique index if not exists ai_knowledge_source_unique
  on new_axe_net.ai_knowledge(source_type, source_table, source_key)
  where source_key is not null and btrim(source_key) <> '';

create index if not exists ai_knowledge_active_domain_idx
  on new_axe_net.ai_knowledge(active, domain, category);

create index if not exists ai_knowledge_updated_idx
  on new_axe_net.ai_knowledge(updated_at desc);

create index if not exists ai_knowledge_title_trgm_idx
  on new_axe_net.ai_knowledge
  using gin (lower(title) extensions.gin_trgm_ops);

create index if not exists ai_knowledge_content_trgm_idx
  on new_axe_net.ai_knowledge
  using gin (lower(content) extensions.gin_trgm_ops);

-- 데이터가 충분히 쌓인 뒤 vector index를 사용합니다.
-- HNSW는 빈 테이블에서도 생성 가능하며 이후 자동 유지됩니다.
create index if not exists ai_knowledge_embedding_hnsw_idx
  on new_axe_net.ai_knowledge
  using hnsw (embedding extensions.vector_cosine_ops)
  where embedding is not null;

-- =========================================================
-- 3. AI 지식 별칭
-- =========================================================
create table if not exists new_axe_net.ai_knowledge_aliases (
  id bigint generated by default as identity primary key,
  knowledge_id bigint not null
    references new_axe_net.ai_knowledge(id)
    on delete cascade,

  alias text not null,
  normalized_alias text generated always as
    (new_axe_net.ai_normalize_text(alias)) stored,

  active boolean not null default true,
  created_by text,
  created_at timestamptz not null default now(),

  constraint ai_knowledge_alias_not_blank
    check (btrim(alias) <> '')
);

create unique index if not exists ai_knowledge_alias_unique
  on new_axe_net.ai_knowledge_aliases(knowledge_id, normalized_alias);

create index if not exists ai_knowledge_alias_lookup_idx
  on new_axe_net.ai_knowledge_aliases(normalized_alias)
  where active = true;

create index if not exists ai_knowledge_alias_trgm_idx
  on new_axe_net.ai_knowledge_aliases
  using gin (lower(alias) extensions.gin_trgm_ops);

-- =========================================================
-- 4. 미답변 질문
-- =========================================================
create table if not exists new_axe_net.ai_unknown_questions (
  id bigint generated by default as identity primary key,

  question text not null,
  normalized_question text generated always as
    (new_axe_net.ai_normalize_text(question)) stored,

  domain text,
  first_user_id text,
  first_nickname text,

  ask_count integer not null default 1
    check (ask_count >= 1),

  status text not null default 'open'
    check (status in ('open', 'resolved', 'ignored')),

  resolved_knowledge_id bigint
    references new_axe_net.ai_knowledge(id)
    on delete set null,

  admin_note text,
  first_asked_at timestamptz not null default now(),
  last_asked_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by text,

  constraint ai_unknown_question_not_blank
    check (btrim(question) <> '')
);

create unique index if not exists ai_unknown_questions_normalized_unique
  on new_axe_net.ai_unknown_questions(normalized_question);

create index if not exists ai_unknown_questions_status_count_idx
  on new_axe_net.ai_unknown_questions(status, ask_count desc, last_asked_at desc);

-- =========================================================
-- 5. 질문 로그
-- =========================================================
create table if not exists new_axe_net.ai_query_logs (
  id bigint generated by default as identity primary key,

  request_id text,
  discord_user_id text,
  discord_nickname text,

  question text not null,
  parsed_domain text,
  parsed_intent text,
  resolved_query text,

  result_status text not null default 'success'
    check (result_status in ('success', 'empty', 'error', 'blocked')),

  match_count integer not null default 0
    check (match_count >= 0),

  search_mode text,
  ai_model text,
  openai_used boolean not null default false,
  cached boolean not null default false,

  top_knowledge_id bigint
    references new_axe_net.ai_knowledge(id)
    on delete set null,

  confidence double precision,
  duration_ms integer,
  error_message text,

  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),

  constraint ai_query_log_question_not_blank
    check (btrim(question) <> ''),
  constraint ai_query_log_duration_nonnegative
    check (duration_ms is null or duration_ms >= 0)
);

create index if not exists ai_query_logs_created_idx
  on new_axe_net.ai_query_logs(created_at desc);

create index if not exists ai_query_logs_result_idx
  on new_axe_net.ai_query_logs(result_status, created_at desc);

create index if not exists ai_query_logs_user_idx
  on new_axe_net.ai_query_logs(discord_user_id, created_at desc);

-- =========================================================
-- 6. updated_at / embedding 무효화
-- =========================================================
create or replace function new_axe_net.ai_knowledge_before_update()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();

  if
    new.title is distinct from old.title
    or new.content is distinct from old.content
    or new.domain is distinct from old.domain
    or new.category is distinct from old.category
  then
    new.embedding := null;
    new.embedding_model := null;
    new.embedding_status := 'pending';
    new.embedding_error := null;
    new.embedded_at := null;
  end if;

  return new;
end;
$$;

drop trigger if exists ai_knowledge_before_update_trigger
on new_axe_net.ai_knowledge;

create trigger ai_knowledge_before_update_trigger
before update on new_axe_net.ai_knowledge
for each row
execute function new_axe_net.ai_knowledge_before_update();

-- =========================================================
-- 7. 미답변 질문 누적 RPC
-- service_role/BOT에서 동일 질문을 반복 기록하면 ask_count만 증가합니다.
-- =========================================================
create or replace function new_axe_net.record_ai_unknown_question(
  p_question text,
  p_domain text default null,
  p_discord_user_id text default null,
  p_discord_nickname text default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_question text := btrim(coalesce(p_question, ''));
  v_normalized text;
  v_id bigint;
begin
  if v_question = '' then
    raise exception '질문이 비어 있습니다.' using errcode = '22023';
  end if;

  v_normalized := new_axe_net.ai_normalize_text(v_question);
  if v_normalized = '' then
    raise exception '검색 가능한 질문이 아닙니다.' using errcode = '22023';
  end if;

  insert into new_axe_net.ai_unknown_questions (
    question,
    domain,
    first_user_id,
    first_nickname,
    ask_count,
    status,
    first_asked_at,
    last_asked_at
  )
  values (
    v_question,
    nullif(btrim(coalesce(p_domain, '')), ''),
    nullif(btrim(coalesce(p_discord_user_id, '')), ''),
    nullif(btrim(coalesce(p_discord_nickname, '')), ''),
    1,
    'open',
    now(),
    now()
  )
  on conflict (normalized_question)
  do update set
    question = excluded.question,
    domain = coalesce(excluded.domain, new_axe_net.ai_unknown_questions.domain),
    ask_count = new_axe_net.ai_unknown_questions.ask_count + 1,
    last_asked_at = now(),
    status = case
      when new_axe_net.ai_unknown_questions.status = 'ignored'
        then 'ignored'
      else 'open'
    end
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function new_axe_net.record_ai_unknown_question(text, text, text, text)
from public, anon, authenticated;

grant execute on function new_axe_net.record_ai_unknown_question(text, text, text, text)
to service_role;

-- =========================================================
-- 8. Hybrid Search RPC
-- keyword(trigram/exact) + semantic(vector cosine) 결합
-- embedding이 아직 없으면 keyword 검색만으로도 동작합니다.
-- =========================================================
create or replace function new_axe_net.search_ai_knowledge(
  p_query_text text,
  p_query_embedding extensions.vector(1536) default null,
  p_domain text default null,
  p_match_count integer default 8,
  p_min_score double precision default 0.20
)
returns table (
  knowledge_id bigint,
  domain text,
  category text,
  title text,
  content text,
  source_type text,
  source_table text,
  source_key text,
  priority integer,
  keyword_score double precision,
  semantic_score double precision,
  final_score double precision,
  matched_alias text
)
language sql
stable
security definer
set search_path = ''
as $$
  with input as (
    select
      btrim(coalesce(p_query_text, '')) as query_text,
      new_axe_net.ai_normalize_text(p_query_text) as query_norm,
      nullif(btrim(coalesce(p_domain, '')), '') as domain_filter,
      least(greatest(coalesce(p_match_count, 8), 1), 30) as result_limit
  ),
  candidates as (
    select
      k.id,
      k.domain,
      k.category,
      k.title,
      k.content,
      k.source_type,
      k.source_table,
      k.source_key,
      k.priority,

      greatest(
        case
          when new_axe_net.ai_normalize_text(k.title) = i.query_norm
            and i.query_norm <> ''
          then 1.0 else 0.0
        end,
        case
          when exists (
            select 1
            from new_axe_net.ai_knowledge_aliases a
            where a.knowledge_id = k.id
              and a.active = true
              and a.normalized_alias = i.query_norm
          )
          then 1.0 else 0.0
        end,
        extensions.similarity(lower(k.title), lower(i.query_text)),
        extensions.similarity(lower(k.content), lower(i.query_text)),
        coalesce((
          select max(extensions.similarity(lower(a.alias), lower(i.query_text)))
          from new_axe_net.ai_knowledge_aliases a
          where a.knowledge_id = k.id
            and a.active = true
        ), 0.0)
      )::double precision as keyword_score,

      case
        when p_query_embedding is not null and k.embedding is not null
        then greatest(0.0, 1.0 - (k.embedding OPERATOR(extensions.<=>) p_query_embedding))
        else 0.0
      end::double precision as semantic_score,

      (
        select a.alias
        from new_axe_net.ai_knowledge_aliases a
        where a.knowledge_id = k.id
          and a.active = true
        order by
          case when a.normalized_alias = i.query_norm then 0 else 1 end,
          extensions.similarity(lower(a.alias), lower(i.query_text)) desc,
          a.id
        limit 1
      ) as matched_alias

    from new_axe_net.ai_knowledge k
    cross join input i
    where k.active = true
      and (i.domain_filter is null or k.domain = i.domain_filter)
  ),
  scored as (
    select
      c.*,
      (
        case
          when p_query_embedding is not null
          then (c.semantic_score * 0.65) + (c.keyword_score * 0.35)
          else c.keyword_score
        end
        + least(greatest(c.priority, -100), 100) * 0.001
      )::double precision as final_score
    from candidates c
  )
  select
    s.id as knowledge_id,
    s.domain,
    s.category,
    s.title,
    s.content,
    s.source_type,
    s.source_table,
    s.source_key,
    s.priority,
    s.keyword_score,
    s.semantic_score,
    s.final_score,
    s.matched_alias
  from scored s
  cross join input i
  where s.final_score >= greatest(coalesce(p_min_score, 0.20), 0.0)
  order by s.final_score desc, s.priority desc, s.id desc
  limit least(greatest(coalesce(p_match_count, 8), 1), 30);
$$;

revoke all on function new_axe_net.search_ai_knowledge(
  text, extensions.vector, text, integer, double precision
) from public, anon, authenticated;

grant execute on function new_axe_net.search_ai_knowledge(
  text, extensions.vector, text, integer, double precision
) to service_role;

-- =========================================================
-- 9. 관리자용 View
-- embedding 자체는 관리 UI에 노출하지 않습니다.
-- =========================================================
create or replace view new_axe_net.ai_knowledge_admin
with (security_invoker = true)
as
select
  k.id,
  k.domain,
  k.category,
  k.title,
  k.content,
  k.source_type,
  k.source_table,
  k.source_key,
  k.priority,
  k.active,
  k.embedding_model,
  k.embedding_status,
  k.embedding_error,
  k.embedded_at,
  k.created_by,
  k.updated_by,
  k.created_at,
  k.updated_at,
  coalesce(
    array_agg(a.alias order by a.alias)
      filter (where a.id is not null and a.active = true),
    array[]::text[]
  ) as aliases
from new_axe_net.ai_knowledge k
left join new_axe_net.ai_knowledge_aliases a
  on a.knowledge_id = k.id
group by k.id;

revoke all on new_axe_net.ai_knowledge_admin from public, anon;
grant select on new_axe_net.ai_knowledge_admin to authenticated, service_role;

-- =========================================================
-- 10. RLS / 권한
-- =========================================================
alter table new_axe_net.ai_knowledge enable row level security;
alter table new_axe_net.ai_knowledge_aliases enable row level security;
alter table new_axe_net.ai_unknown_questions enable row level security;
alter table new_axe_net.ai_query_logs enable row level security;

revoke all on table new_axe_net.ai_knowledge from public, anon, authenticated;
revoke all on table new_axe_net.ai_knowledge_aliases from public, anon, authenticated;
revoke all on table new_axe_net.ai_unknown_questions from public, anon, authenticated;
revoke all on table new_axe_net.ai_query_logs from public, anon, authenticated;

-- service_role / BOT / Vercel 서버
grant select, insert, update, delete on table new_axe_net.ai_knowledge to service_role;
grant select, insert, update, delete on table new_axe_net.ai_knowledge_aliases to service_role;
grant select, insert, update, delete on table new_axe_net.ai_unknown_questions to service_role;
grant select, insert, update, delete on table new_axe_net.ai_query_logs to service_role;
grant usage, select on all sequences in schema new_axe_net to service_role;

-- 관리자 브라우저: RLS를 통과하는 경우에만 관리 가능
grant select, insert, update, delete on table new_axe_net.ai_knowledge to authenticated;
grant select, insert, update, delete on table new_axe_net.ai_knowledge_aliases to authenticated;
grant select, insert, update, delete on table new_axe_net.ai_unknown_questions to authenticated;
grant select on table new_axe_net.ai_query_logs to authenticated;

drop policy if exists ai_knowledge_admin_all
on new_axe_net.ai_knowledge;
create policy ai_knowledge_admin_all
on new_axe_net.ai_knowledge
for all to authenticated
using (new_axe_net.is_admin())
with check (new_axe_net.is_admin());

drop policy if exists ai_knowledge_aliases_admin_all
on new_axe_net.ai_knowledge_aliases;
create policy ai_knowledge_aliases_admin_all
on new_axe_net.ai_knowledge_aliases
for all to authenticated
using (new_axe_net.is_admin())
with check (new_axe_net.is_admin());

drop policy if exists ai_unknown_questions_admin_all
on new_axe_net.ai_unknown_questions;
create policy ai_unknown_questions_admin_all
on new_axe_net.ai_unknown_questions
for all to authenticated
using (new_axe_net.is_admin())
with check (new_axe_net.is_admin());

drop policy if exists ai_query_logs_admin_read
on new_axe_net.ai_query_logs;
create policy ai_query_logs_admin_read
on new_axe_net.ai_query_logs
for select to authenticated
using (new_axe_net.is_admin());

-- =========================================================
-- 11. 초기 테스트 지식 1건
-- 실제 운영 정보가 아닌 연결 확인용이며 active=false 상태입니다.
-- =========================================================
insert into new_axe_net.ai_knowledge (
  domain,
  category,
  title,
  content,
  source_type,
  source_table,
  source_key,
  priority,
  active,
  created_by,
  updated_by
)
values (
  'system',
  'test',
  'AXE AI 연결 테스트',
  'AXE AI Supabase 지식 저장소 연결 확인용 비활성 테스트 데이터입니다.',
  'manual',
  'ai_knowledge',
  'system:test:v1',
  -100,
  false,
  'migration:045',
  'migration:045'
)
on conflict (source_type, source_table, source_key)
where source_key is not null and btrim(source_key) <> ''
do nothing;

notify pgrst, 'reload schema';

commit;

-- =========================================================
-- 실행 후 확인용 (선택)
-- =========================================================
-- select id, domain, title, active, embedding_status
-- from new_axe_net.ai_knowledge
-- order by id desc
-- limit 10;
--
-- select *
-- from new_axe_net.search_ai_knowledge(
--   p_query_text := 'AXE AI 연결 테스트',
--   p_query_embedding := null,
--   p_domain := null,
--   p_match_count := 5,
--   p_min_score := 0.1
-- );
