-- AXE NET v1.47.0
-- 추천세팅 게시글 / 슬롯 조합 / 내 프리셋(즐겨찾기)

set search_path = new_axe_net, public;

create table if not exists info_preset_posts (
  id bigint generated by default as identity primary key,
  system_key text unique,
  author_member_key text references members(member_key) on update cascade on delete set null,
  author_nickname text not null default 'AXE',
  title text not null,
  description text not null default '',
  tags text[] not null default '{}'::text[],
  favorite_count integer not null default 0 check (favorite_count >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint info_preset_posts_title_len check (char_length(title) between 1 and 100),
  constraint info_preset_posts_description_len check (char_length(description) <= 4000)
);

create table if not exists info_preset_post_slots (
  id bigint generated by default as identity primary key,
  post_id bigint not null references info_preset_posts(id) on delete cascade,
  slot_key text not null check (slot_key in ('outer','top','bottom','shoes')),
  prefix_modbook_id bigint references info_modbooks(id) on delete set null,
  suffix_modbook_id bigint references info_modbooks(id) on delete set null,
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (post_id, slot_key),
  constraint info_preset_post_slots_note_len check (char_length(note) <= 500)
);

create table if not exists member_preset_favorites (
  member_key text not null references members(member_key) on update cascade on delete cascade,
  post_id bigint not null references info_preset_posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (member_key, post_id)
);

create index if not exists info_preset_posts_active_updated_idx
  on info_preset_posts (active, updated_at desc, id desc);
create index if not exists info_preset_post_slots_post_idx
  on info_preset_post_slots (post_id, slot_key);
create index if not exists member_preset_favorites_post_idx
  on member_preset_favorites (post_id);

alter table info_preset_posts enable row level security;
alter table info_preset_post_slots enable row level security;
alter table member_preset_favorites enable row level security;

drop policy if exists info_preset_posts_public_read on info_preset_posts;
create policy info_preset_posts_public_read
  on info_preset_posts for select
  using (active = true);

drop policy if exists info_preset_post_slots_public_read on info_preset_post_slots;
create policy info_preset_post_slots_public_read
  on info_preset_post_slots for select
  using (
    exists (
      select 1
      from info_preset_posts p
      where p.id = info_preset_post_slots.post_id
        and p.active = true
    )
  );

-- 즐겨찾기는 커스텀 멤버 세션 API(service role)에서만 접근합니다.
revoke all on table member_preset_favorites from anon, authenticated;

grant select on table info_preset_posts to anon, authenticated;
grant select on table info_preset_post_slots to anon, authenticated;
grant all on table info_preset_posts to service_role;
grant all on table info_preset_post_slots to service_role;
grant all on table member_preset_favorites to service_role;
grant usage, select on sequence info_preset_posts_id_seq to service_role;
grant usage, select on sequence info_preset_post_slots_id_seq to service_role;

create or replace function preset_slot_label(p_slot_key text)
returns text
language sql
immutable
as $$
  select case p_slot_key
    when 'outer' then '겉옷'
    when 'top' then '상의'
    when 'bottom' then '하의'
    when 'shoes' then '신발'
    else ''
  end;
$$;

create or replace function save_info_preset_post(
  p_id bigint,
  p_member_key text,
  p_nickname text,
  p_title text,
  p_description text,
  p_tags text[],
  p_slots jsonb,
  p_allow_override boolean default false
)
returns bigint
language plpgsql
security definer
set search_path = new_axe_net, public
as $$
declare
  v_id bigint;
  v_owner text;
  v_slot jsonb;
  v_slot_key text;
  v_slot_label text;
  v_prefix_id bigint;
  v_suffix_id bigint;
  v_note text;
  v_type text;
  v_parts text;
begin
  if nullif(trim(coalesce(p_member_key, '')), '') is null then
    raise exception '멤버 정보가 없습니다.';
  end if;
  if char_length(trim(coalesce(p_title, ''))) < 1 or char_length(trim(coalesce(p_title, ''))) > 100 then
    raise exception '제목은 1~100자로 입력하세요.';
  end if;
  if char_length(coalesce(p_description, '')) > 4000 then
    raise exception '설명은 4000자 이하로 입력하세요.';
  end if;
  if jsonb_typeof(coalesce(p_slots, '[]'::jsonb)) <> 'array' then
    raise exception '장비 슬롯 정보가 올바르지 않습니다.';
  end if;

  if p_id is null then
    insert into info_preset_posts (
      author_member_key, author_nickname, title, description, tags, active, created_at, updated_at
    ) values (
      p_member_key,
      coalesce(nullif(trim(p_nickname), ''), 'AXE'),
      trim(p_title),
      coalesce(p_description, ''),
      coalesce(p_tags, '{}'::text[]),
      true,
      now(),
      now()
    ) returning id into v_id;
  else
    select author_member_key into v_owner
    from info_preset_posts
    where id = p_id;

    if not found then
      raise exception '수정할 추천세팅 게시글을 찾을 수 없습니다.';
    end if;
    if coalesce(v_owner, '') <> p_member_key and not p_allow_override then
      raise exception '본인이 작성한 추천세팅만 수정할 수 있습니다.';
    end if;

    update info_preset_posts
    set title = trim(p_title),
        description = coalesce(p_description, ''),
        tags = coalesce(p_tags, '{}'::text[]),
        active = true,
        updated_at = now()
    where id = p_id;

    v_id := p_id;
    delete from info_preset_post_slots where post_id = v_id;
  end if;

  for v_slot in select * from jsonb_array_elements(coalesce(p_slots, '[]'::jsonb))
  loop
    v_slot_key := trim(coalesce(v_slot->>'slot_key', ''));
    if v_slot_key not in ('outer','top','bottom','shoes') then
      raise exception '지원하지 않는 장비 부위입니다: %', v_slot_key;
    end if;
    v_slot_label := preset_slot_label(v_slot_key);

    v_prefix_id := nullif(v_slot->>'prefix_modbook_id', '')::bigint;
    v_suffix_id := nullif(v_slot->>'suffix_modbook_id', '')::bigint;
    v_note := left(coalesce(v_slot->>'note', ''), 500);

    if v_prefix_id is not null then
      select type, parts into v_type, v_parts
      from info_modbooks
      where id = v_prefix_id and active = true;
      if not found then raise exception '선택한 접두 개조서를 찾을 수 없습니다.'; end if;
      if v_type <> '접두' then raise exception '접두 슬롯에는 접두 개조서만 선택할 수 있습니다.'; end if;
      if not (v_slot_label = any(regexp_split_to_array(coalesce(v_parts,''), '\s*,\s*'))) then
        raise exception '% 부위에 적용할 수 없는 접두 개조서입니다.', v_slot_label;
      end if;
    end if;

    if v_suffix_id is not null then
      select type, parts into v_type, v_parts
      from info_modbooks
      where id = v_suffix_id and active = true;
      if not found then raise exception '선택한 접미 개조서를 찾을 수 없습니다.'; end if;
      if v_type <> '접미' then raise exception '접미 슬롯에는 접미 개조서만 선택할 수 있습니다.'; end if;
      if not (v_slot_label = any(regexp_split_to_array(coalesce(v_parts,''), '\s*,\s*'))) then
        raise exception '% 부위에 적용할 수 없는 접미 개조서입니다.', v_slot_label;
      end if;
    end if;

    insert into info_preset_post_slots (
      post_id, slot_key, prefix_modbook_id, suffix_modbook_id, note, updated_at
    ) values (
      v_id, v_slot_key, v_prefix_id, v_suffix_id, v_note, now()
    );
  end loop;

  if not exists (
    select 1 from info_preset_post_slots s
    where s.post_id = v_id
      and (s.prefix_modbook_id is not null or s.suffix_modbook_id is not null)
  ) then
    raise exception '개조서를 하나 이상 선택하세요.';
  end if;

  return v_id;
end;
$$;

create or replace function delete_info_preset_post(
  p_id bigint,
  p_member_key text,
  p_allow_override boolean default false
)
returns boolean
language plpgsql
security definer
set search_path = new_axe_net, public
as $$
declare
  v_owner text;
begin
  select author_member_key into v_owner
  from info_preset_posts
  where id = p_id;
  if not found then return false; end if;
  if coalesce(v_owner, '') <> p_member_key and not p_allow_override then
    raise exception '본인이 작성한 추천세팅만 삭제할 수 있습니다.';
  end if;
  delete from member_preset_favorites where post_id = p_id;
  update info_preset_posts set active = false, updated_at = now() where id = p_id;
  return true;
end;
$$;

create or replace function refresh_info_preset_favorite_count()
returns trigger
language plpgsql
security definer
set search_path = new_axe_net, public
as $$
declare
  v_post_id bigint;
begin
  if tg_op = 'DELETE' then
    v_post_id := old.post_id;
  else
    v_post_id := new.post_id;
  end if;

  update info_preset_posts
  set favorite_count = (
    select count(*)::integer from member_preset_favorites f
    where f.post_id = v_post_id
  )
  where id = v_post_id;

  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

drop trigger if exists trg_info_preset_favorite_count_ins on member_preset_favorites;
create trigger trg_info_preset_favorite_count_ins
  after insert on member_preset_favorites
  for each row execute function refresh_info_preset_favorite_count();

drop trigger if exists trg_info_preset_favorite_count_del on member_preset_favorites;
create trigger trg_info_preset_favorite_count_del
  after delete on member_preset_favorites
  for each row execute function refresh_info_preset_favorite_count();

revoke all on function save_info_preset_post(bigint,text,text,text,text,text[],jsonb,boolean) from public, anon, authenticated;
revoke all on function delete_info_preset_post(bigint,text,boolean) from public, anon, authenticated;
grant execute on function save_info_preset_post(bigint,text,text,text,text,text[],jsonb,boolean) to service_role;
grant execute on function delete_info_preset_post(bigint,text,boolean) to service_role;

-- 현재 고정 추천세팅을 첫 게시글로 이관합니다.
insert into info_preset_posts (
  system_key, author_member_key, author_nickname, title, description, tags, active
) values (
  'movement-tier1', null, 'AXE', '이동속도 1티어',
  '최대 옵션 기준으로 이동속도를 우선하고, 실사용 효율이 좋은 보조 옵션을 함께 챙긴 AXE 추천 세팅입니다.',
  array['이동속도','밸런스','AXE 추천'], true
)
on conflict (system_key) do update
set title = excluded.title,
    description = excluded.description,
    tags = excluded.tags,
    active = true,
    updated_at = now();

with p as (
  select id from info_preset_posts where system_key = 'movement-tier1'
), slot_values as (
  select 'outer'::text as slot_key,
    (select id from info_modbooks where active = true and type = '접두' and name ilike '기운찬%' order by id limit 1) as prefix_id,
    (select id from info_modbooks where active = true and type = '접미' and name ilike '바람의%' order by id limit 1) as suffix_id,
    '이동속도 중심 겉옷 조합'::text as note
  union all
  select 'top', null,
    (select id from info_modbooks where active = true and type = '접미' and name ilike '전력질주의%' order by id limit 1),
    '이동속도용 접두는 비워둔 구성'
  union all
  select 'bottom',
    (select id from info_modbooks where active = true and type = '접두' and name ilike '잡기 힘든%' order by id limit 1),
    (select id from info_modbooks where active = true and type = '접미' and name ilike '쾌속의%' order by id limit 1),
    '바람의보다 이동속도는 1% 낮지만 최대 스태미나를 함께 챙기는 밸런스 조합'
  union all
  select 'shoes',
    (select id from info_modbooks where active = true and type = '접두' and name ilike '기운찬%' order by id limit 1),
    (select id from info_modbooks where active = true and type = '접미' and name ilike '레이서의%' order by id limit 1),
    '이동속도 최고치를 노리는 신발 조합. 전력질주 스킬 경험치 패널티에 주의'
)
insert into info_preset_post_slots (post_id, slot_key, prefix_modbook_id, suffix_modbook_id, note)
select p.id, s.slot_key, s.prefix_id, s.suffix_id, s.note
from p cross join slot_values s
on conflict (post_id, slot_key) do update
set prefix_modbook_id = excluded.prefix_modbook_id,
    suffix_modbook_id = excluded.suffix_modbook_id,
    note = excluded.note,
    updated_at = now();
