-- AXE NET · SYSTEM RUNTIME CONTROL R1
-- 053_system_runtime_control.sql
-- AXE WAR Supabase 프로젝트 > SQL Editor에서 1회 실행
--
-- 목적
-- 1) AXE NET / AXE BOT 운영 상태를 중앙에서 저장
-- 2) 상태 조회는 공개 가능하되, 변경은 최고관리자(superadmin)만 허용
-- 3) 모든 변경 이력을 감사 로그로 보존
-- 4) OFF는 데이터 삭제나 서버 종료가 아니라 서비스 기능 차단 상태를 의미

create schema if not exists new_axe_net;

create table if not exists new_axe_net.runtime_controls (
  system_key text primary key,
  enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  constraint runtime_controls_system_key_check
    check (system_key in ('axe_net', 'axe_bot'))
);

insert into new_axe_net.runtime_controls (system_key, enabled)
values
  ('axe_net', true),
  ('axe_bot', true)
on conflict (system_key) do nothing;

create table if not exists new_axe_net.runtime_control_audit (
  id bigint generated by default as identity primary key,
  system_key text not null,
  previous_enabled boolean not null,
  enabled boolean not null,
  changed_by uuid references auth.users(id) on delete set null,
  changed_by_member_key text,
  changed_at timestamptz not null default now(),
  constraint runtime_control_audit_system_key_check
    check (system_key in ('axe_net', 'axe_bot'))
);

create index if not exists runtime_control_audit_changed_at_idx
on new_axe_net.runtime_control_audit (changed_at desc);

alter table new_axe_net.runtime_controls enable row level security;
alter table new_axe_net.runtime_control_audit enable row level security;

revoke all on table new_axe_net.runtime_controls from public, anon, authenticated;
revoke all on table new_axe_net.runtime_control_audit from public, anon, authenticated;
revoke all on sequence new_axe_net.runtime_control_audit_id_seq from public, anon, authenticated;

grant usage on schema new_axe_net to anon, authenticated, service_role;
grant select, insert, update, delete on table new_axe_net.runtime_controls to service_role;
grant select, insert on table new_axe_net.runtime_control_audit to service_role;
grant usage, select on sequence new_axe_net.runtime_control_audit_id_seq to service_role;

-- 공개 상태 조회. 운영 여부 외의 민감정보는 노출하지 않습니다.
create or replace function new_axe_net.get_runtime_controls()
returns table (
  system_key text,
  enabled boolean,
  updated_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  select c.system_key, c.enabled, c.updated_at
  from new_axe_net.runtime_controls c
  where c.system_key in ('axe_net', 'axe_bot')
  order by c.system_key;
$$;

revoke all on function new_axe_net.get_runtime_controls() from public;
grant execute on function new_axe_net.get_runtime_controls() to anon, authenticated, service_role;

-- 최고관리자 전용 변경 함수.
create or replace function new_axe_net.set_runtime_control(
  p_system_key text,
  p_enabled boolean
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_key text := lower(btrim(coalesce(p_system_key, '')));
  v_previous boolean;
  v_member_key text;
begin
  if not new_axe_net.is_superadmin() then
    raise exception '최고관리자 권한이 필요합니다.' using errcode = '42501';
  end if;

  if v_key not in ('axe_net', 'axe_bot') then
    raise exception '지원하지 않는 시스템 키입니다.' using errcode = '22023';
  end if;

  select c.enabled
    into v_previous
  from new_axe_net.runtime_controls c
  where c.system_key = v_key
  for update;

  if not found then
    raise exception '시스템 상태 행을 찾을 수 없습니다.' using errcode = 'P0002';
  end if;

  select a.member_key
    into v_member_key
  from new_axe_net.admin_accounts a
  where a.user_id = auth.uid()
    and a.enabled = true
    and a.admin_level = 'superadmin'
  limit 1;

  update new_axe_net.runtime_controls
     set enabled = p_enabled,
         updated_at = now(),
         updated_by = auth.uid()
   where system_key = v_key;

  if v_previous is distinct from p_enabled then
    insert into new_axe_net.runtime_control_audit (
      system_key,
      previous_enabled,
      enabled,
      changed_by,
      changed_by_member_key
    ) values (
      v_key,
      v_previous,
      p_enabled,
      auth.uid(),
      v_member_key
    );
  end if;

  return jsonb_build_object(
    'system_key', v_key,
    'enabled', p_enabled,
    'previous_enabled', v_previous,
    'updated_at', now()
  );
end;
$$;

revoke all on function new_axe_net.set_runtime_control(text, boolean) from public, anon;
grant execute on function new_axe_net.set_runtime_control(text, boolean) to authenticated;

notify pgrst, 'reload schema';
